import express from 'express';
import { DatabaseSync } from 'node:sqlite';
import bcrypt from 'bcryptjs';
import cookieParser from 'cookie-parser';
import { randomBytes } from 'node:crypto';
import fs from 'node:fs';

fs.mkdirSync('data', { recursive: true });
const db = new DatabaseSync('data/gatherhall.sqlite');
db.exec(`PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS tenants(id TEXT PRIMARY KEY,name TEXT); CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,tenant TEXT,name TEXT,email TEXT UNIQUE,password TEXT,role TEXT); CREATE TABLE IF NOT EXISTS account_links(record_id TEXT PRIMARY KEY,user_id TEXT); CREATE TABLE IF NOT EXISTS client_access(user_id TEXT PRIMARY KEY,client_id TEXT); CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id TEXT,expires INTEGER); CREATE TABLE IF NOT EXISTS records(id TEXT PRIMARY KEY,tenant TEXT,kind TEXT,body TEXT);`);
const put=(id,tenant,kind,body)=>db.prepare('INSERT INTO records VALUES(?,?,?,?)').run(id,tenant,kind,JSON.stringify(body));
if(!db.prepare('SELECT id FROM tenants LIMIT 1').get()){
 for(const [tid,name] of [['t1','The Grand Estate'],['t2','Willow & Co. Venues']]){
 db.prepare('INSERT INTO tenants VALUES(?,?)').run(tid,name);
 for(const [role,person,email] of [['owner','Arjun Mehta',tid==='t1'?'owner@gatherhall.demo':'willow@gatherhall.demo'],['staff','Ananya Sharma',tid==='t1'?'staff@gatherhall.demo':'team@willow.demo'],['client','Priya Sharma',tid==='t1'?'client@gatherhall.demo':'client@willow.demo']]) db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?)').run(tid+role,tid,person,email,bcrypt.hashSync('Welcome123!',10),role);
 const halls=[['The Grand Ballroom','Indoor','500','185000','venue.jpg'],['The Garden Pavilion','Outdoor','300','125000','garden.jpg'],['The Royal Terrace','Rooftop','200','95000','terrace.jpg']];
 halls.forEach((h,i)=>put(tid+'h'+i,tid,'halls',{name:h[0],type:h[1],capacity:+h[2],price:+h[3],image:h[4],status:'Available',description:['Timeless elegance, crystal chandeliers, and room for your biggest moments.','An open-air celebration surrounded by lush gardens and warm lights.','An intimate rooftop setting with beautiful sunset views.'][i]}));
 const clients=[['Priya Sharma','priya.sharma@gmail.com','+91 98765 43210'],['Rohan Kapoor','rohan.k@gmail.com','+91 98234 56100'],['Ananya Patel','ananya.p@gmail.com','+91 99876 54321'],['Vikram Singh','vikram.s@gmail.com','+91 97654 32109'],['Meera Joshi','meera.j@gmail.com','+91 98761 23450'],['Aditya Rao','aditya.r@gmail.com','+91 99123 45678']];
 clients.forEach((c,i)=>put(tid+'c'+i,tid,'clients',{name:c[0],email:c[1],phone:c[2],notes:'',status:'Active'}));
 [['Ananya Sharma','Event manager','ananya@gatherhall.demo'],['Rahul Verma','Operations','rahul@gatherhall.demo'],['Neha Desai','Guest relations','neha@gatherhall.demo'],['Kabir Shah','Venue coordinator','kabir@gatherhall.demo']].forEach((s,i)=>put(tid+'s'+i,tid,'staff',{name:s[0],position:s[1],email:s[2],phone:'+91 98765 '+(43210+i),status:'Active'}));
 for(let i=0;i<36;i++){
 const ci=i%6,hi=i%3,up=i<6; const date=up?['2026-09-29','2026-09-30','2026-10-02','2026-10-04','2026-10-08','2026-10-12'][i]:`2026-${String(4+Math.floor((i-6)/5)).padStart(2,'0')}-${String(3+((i*3)%24)).padStart(2,'0')}`;
 const total=[185000,125000,95000][hi]; const status=up?(i===2||i===4?'Pending':'Confirmed'):'Completed';
 put(tid+'b'+i,tid,'bookings',{name:up?['Priya & Arjun','Rohan & Sneha','Ananya & Karan','Vikram & Aisha','Meera’s engagement','Aditya & Nisha'][i]:[clients[ci][0].split(' ')[0]+' & Family','The Kapoor celebration','Patel wedding reception'][hi],clientId:tid+'c'+ci,client:clients[ci][0],hallId:tid+'h'+hi,hall:halls[hi][0],date,time:hi===1?'10:00':'18:00',guests:[350,220,150][hi],type:i%5===4?'Engagement':'Wedding',status,total,notes:up?'Floral décor and welcome refreshments included.':''});
 put(tid+'p'+i,tid,'payments',{bookingId:tid+'b'+i,client:clients[ci][0],amount:up?Math.round(total*.5):total,date:up?'2026-09-20':date,method:i%2?'Bank transfer':'UPI',status:'Paid',reference:'GH-'+(2026001+i)});
 }
 }
}
for(const tid of ['t1','t2']){db.prepare('INSERT OR IGNORE INTO client_access VALUES(?,?)').run(tid+'client',tid+'c0');db.prepare('INSERT OR IGNORE INTO account_links VALUES(?,?)').run(tid+'c0',tid+'client');db.prepare('INSERT OR IGNORE INTO account_links VALUES(?,?)').run(tid+'s0',tid+'staff');}
const app=express();app.use(express.json());app.use(cookieParser());
const publicUser=u=>({id:u.id,name:u.name,email:u.email,role:u.role,tenantId:u.tenant,tenant:db.prepare('SELECT name FROM tenants WHERE id=?').get(u.tenant).name});
app.post('/api/auth/login',(req,res)=>{const u=db.prepare('SELECT * FROM users WHERE email=?').get(String(req.body.email||'').toLowerCase());if(!u||!bcrypt.compareSync(req.body.password||'',u.password))return res.status(401).json({error:'Email or password is incorrect.'});const linked=db.prepare('SELECT body FROM records JOIN account_links ON records.id=account_links.record_id WHERE account_links.user_id=?').get(u.id);if(linked&&JSON.parse(linked.body).status==='Inactive')return res.status(403).json({error:'This account is inactive. Contact your workspace owner.'});const token=randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(token,u.id,Date.now()+604800000);res.cookie('session',token,{httpOnly:true,sameSite:'lax',maxAge:604800000});res.json(publicUser(u));});
app.post('/api/auth/register',(req,res)=>{const {name,email,password,organization}=req.body;if(!name||!organization||!email?.includes('@')||password?.length<8)return res.status(400).json({error:'Complete all fields and use a password with at least 8 characters.'});if(db.prepare('SELECT id FROM users WHERE email=?').get(email.toLowerCase()))return res.status(409).json({error:'This email is already registered.'});const tid=randomBytes(8).toString('hex'),id=randomBytes(8).toString('hex');db.prepare('INSERT INTO tenants VALUES(?,?)').run(tid,organization);db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?)').run(id,tid,name,email.toLowerCase(),bcrypt.hashSync(password,10),'owner');res.json({success:true});});
app.post('/api/auth/logout',(req,res)=>{db.prepare('DELETE FROM sessions WHERE token=?').run(req.cookies.session||'');res.clearCookie('session').json({success:true});});
app.use('/api',(req,res,next)=>{const u=db.prepare('SELECT users.* FROM users JOIN sessions ON users.id=sessions.user_id WHERE token=? AND expires>?').get(req.cookies.session||'',Date.now());if(!u)return res.status(401).json({error:'Please sign in to continue.'});const linked=db.prepare('SELECT body FROM records JOIN account_links ON records.id=account_links.record_id WHERE account_links.user_id=?').get(u.id);if(linked&&JSON.parse(linked.body).status==='Inactive')return res.status(403).json({error:'This account is inactive. Contact your workspace owner.'});req.user=u;next();});
app.get('/api/auth/me',(req,res)=>res.json(publicUser(req.user)));
const list=(tenant,kind)=>db.prepare('SELECT * FROM records WHERE tenant=? AND kind=?').all(tenant,kind).map(r=>({...JSON.parse(r.body),id:r.id}));
function visible(req,kind){let rows=list(req.user.tenant,kind);if(req.user.role==='client'){const access=db.prepare('SELECT client_id FROM client_access WHERE user_id=?').get(req.user.id);const cs=access?[access.client_id]:[];const bs=list(req.user.tenant,'bookings').filter(b=>cs.includes(b.clientId));if(kind==='clients')rows=rows.filter(c=>cs.includes(c.id));if(kind==='bookings')rows=bs;if(kind==='payments')rows=rows.filter(p=>bs.some(b=>b.id===p.bookingId));if(kind==='staff')rows=[];}return rows;}
app.get('/api/data',(req,res)=>res.json(Object.fromEntries(['halls','bookings','clients','payments','staff'].map(k=>[k,visible(req,k)]))));
const fields={halls:['name','type','capacity','price','image','status','description'],bookings:['name','clientId','client','hallId','hall','date','time','guests','type','status','total','notes'],clients:['name','email','phone','notes','status'],staff:['name','email','phone','position','status'],payments:['bookingId','client','amount','date','method','status','reference']};
function access(req,res,next){const kind=req.params.kind;if(!fields[kind])return res.status(404).json({error:'Resource not found.'});if(req.user.role==='client'&&(kind!=='bookings'||req.method!=='POST'))return res.status(403).json({error:'This action requires a team member.'});if(req.user.role==='staff'&&['halls','staff'].includes(kind))return res.status(403).json({error:'Only owners can manage halls and staff.'});next();}
function validate(req,body,id){const kind=req.params.kind;const data=Object.fromEntries(fields[kind].filter(k=>body[k]!==undefined).map(k=>[k,body[k]]));for(const k of ['name','email','phone','description','notes','position'])if(data[k]!==undefined)data[k]=String(data[k]).trim().slice(0,2000);
 if(kind==='bookings'){
 const hall=list(req.user.tenant,'halls').find(h=>h.id===data.hallId);const client=visible(req,'clients').find(c=>c.id===data.clientId);if(!hall||!client)throw Error('Select a valid hall and client.');if(hall.status==='Maintenance'&&!id)throw Error('This hall is under maintenance. Please choose an available hall.');if(!/^\d{4}-\d{2}-\d{2}$/.test(data.date)||isNaN(Date.parse(data.date)))throw Error('Enter a valid event date.');if(!data.name||!data.time)throw Error('Event name and time are required.');if(!Number.isFinite(+data.guests)||+data.guests<1||+data.guests>hall.capacity)throw Error(`Guest count must be between 1 and ${hall.capacity}.`);if(list(req.user.tenant,'bookings').some(b=>b.id!==id&&b.hallId===hall.id&&b.date===data.date&&b.status!=='Cancelled'))throw Error('This hall is already booked on that date. Please choose another hall or date.');data.hall=hall.name;data.client=client.name;if(req.user.role==='client'){data.status='Pending';data.total=hall.price;}if(!['Confirmed','Pending','Completed','Cancelled'].includes(data.status))throw Error('Choose a valid booking status.');
 }
 if(['clients','staff','halls'].includes(kind)&&!data.name)throw Error('Name is required.');
 for(const k of ['capacity','price','total','guests','amount'])if(data[k]!==undefined){data[k]=Number(data[k]);if(!Number.isFinite(data[k])||data[k]<0)throw Error(`${k} must be a positive number.`);}
 if(['clients','staff'].includes(kind)&&!String(data.email||'').match(/^[^\s@]+@[^\s@]+\.[^\s@]+$/))throw Error('Enter a valid email address.');
 if(kind==='payments'){const booking=list(req.user.tenant,'bookings').find(b=>b.id===data.bookingId);if(!booking)throw Error('Choose a valid booking.');if(!data.amount||!data.date)throw Error('Amount and payment date are required.');const paid=list(req.user.tenant,'payments').filter(p=>p.bookingId===booking.id&&p.id!==id).reduce((a,p)=>a+p.amount,0);if(paid+data.amount>booking.total)throw Error('Payment exceeds the remaining balance.');data.client=booking.client;data.status='Paid';}
 return data;
}
function provision(req,id,data){
 if(!req.body.loginPassword)return;
 if(req.user.role!=='owner'||!['clients','staff'].includes(req.params.kind))throw Error('Only owners can grant workspace access.');
 if(typeof req.body.loginPassword!=='string'||req.body.loginPassword.length<8)throw Error('The account password must have at least 8 characters.');
 const email=data.email.toLowerCase();
 if(db.prepare('SELECT id FROM users WHERE email=?').get(email))throw Error('An account with this email already exists. Leave the account password empty to update the directory record only.');
 if(db.prepare('SELECT user_id FROM account_links WHERE record_id=?').get(id))throw Error('This contact already has workspace access. Leave the password empty to update their directory details.');const uid=randomBytes(8).toString('hex');
 db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?)').run(uid,req.user.tenant,data.name,email,bcrypt.hashSync(req.body.loginPassword,10),req.params.kind==='clients'?'client':'staff');
 db.prepare('INSERT INTO account_links VALUES(?,?)').run(id,uid);if(req.params.kind==='clients')db.prepare('INSERT INTO client_access VALUES(?,?)').run(uid,id);
}
app.put('/api/settings/profile',(req,res)=>{if(!req.body.name?.trim())return res.status(400).json({error:'Name is required.'});db.prepare('UPDATE users SET name=? WHERE id=?').run(req.body.name.trim(),req.user.id);if(req.user.role==='owner'&&req.body.organization?.trim())db.prepare('UPDATE tenants SET name=? WHERE id=?').run(req.body.organization.trim(),req.user.tenant);res.json(publicUser(db.prepare('SELECT * FROM users WHERE id=?').get(req.user.id)));});
app.post('/api/:kind',access,(req,res)=>{try{const data=validate(req,req.body);const id=randomBytes(8).toString('hex');db.exec('BEGIN');put(id,req.user.tenant,req.params.kind,data);provision(req,id,data);db.exec('COMMIT');res.status(201).json({...data,id});}catch(e){if(db.isTransaction)db.exec('ROLLBACK');res.status(400).json({error:e.message});}});
app.put('/api/:kind/:id',access,(req,res)=>{const row=db.prepare('SELECT * FROM records WHERE id=? AND tenant=? AND kind=?').get(req.params.id,req.user.tenant,req.params.kind);if(!row)return res.status(404).json({error:'Record not found.'});try{const data=validate(req,req.body,req.params.id);db.exec('BEGIN');db.prepare('UPDATE records SET body=? WHERE id=?').run(JSON.stringify(data),row.id);provision(req,row.id,data);db.exec('COMMIT');res.json({...data,id:row.id});}catch(e){if(db.isTransaction)db.exec('ROLLBACK');res.status(400).json({error:e.message});}});
app.delete('/api/:kind/:id',access,(req,res)=>{const {id,kind}=req.params;const row=db.prepare('SELECT * FROM records WHERE id=? AND tenant=? AND kind=?').get(id,req.user.tenant,kind);if(!row)return res.status(404).json({error:'Record not found.'});if((kind==='halls'&&list(req.user.tenant,'bookings').some(b=>b.hallId===id))||(kind==='clients'&&list(req.user.tenant,'bookings').some(b=>b.clientId===id)))return res.status(409).json({error:'This record has bookings. Remove its bookings before deleting it.'});if(kind==='bookings')for(const p of list(req.user.tenant,'payments').filter(p=>p.bookingId===id))db.prepare('DELETE FROM records WHERE id=? AND tenant=?').run(p.id,req.user.tenant);const link=db.prepare('SELECT user_id FROM account_links WHERE record_id=?').get(id);if(link){db.prepare('DELETE FROM sessions WHERE user_id=?').run(link.user_id);db.prepare('DELETE FROM client_access WHERE user_id=?').run(link.user_id);db.prepare('DELETE FROM users WHERE id=? AND tenant=?').run(link.user_id,req.user.tenant);db.prepare('DELETE FROM account_links WHERE record_id=?').run(id);}db.prepare('DELETE FROM records WHERE id=? AND tenant=?').run(id,req.user.tenant);res.json({success:true});});

if(process.env.NODE_ENV==='production'){app.use(express.static('dist'));app.get('*',(req,res)=>res.sendFile(process.cwd()+'/dist/index.html'));}else{const {createServer}=await import('vite');const vite=await createServer({server:{middlewareMode:true,allowedHosts:true},appType:'spa'});app.use(vite.middlewares);}
app.listen(3000,'0.0.0.0',()=>console.log('Gatherhall running on port 3000'));
