import assert from 'node:assert/strict';
const base=process.env.TEST_URL||'http://localhost:3000/api';
async function request(path,method='GET',body,cookie){const r=await fetch(base+path,{method,headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}
async function login(role){const r=await request('/auth/login','POST',{email:role+'@gatherhall.demo',password:'Welcome123!'});assert.equal(r.status,200);return r.cookie;}
assert.equal((await request('/data')).status,401);
assert.equal((await request('/auth/login','POST',{email:'owner@gatherhall.demo',password:'wrong'})).status,401);
const owner=await login('owner'),staff=await login('staff'),client=await login('client');
const all=(await request('/data','GET',null,owner)).data;
assert.ok(all.bookings.length>=36);assert.equal(all.halls.length,3);
const mine=(await request('/data','GET',null,client)).data;
assert.equal((await request('/availability?date=2026-09-29')).status,401);
assert.equal((await request('/availability?date=2026-02-30','GET',null,owner)).status,400);
assert.equal((await request('/availability?date=bad-date','GET',null,owner)).status,400);
const ownerAvailability=await request('/availability?date=2026-09-29','GET',null,owner);
assert.equal(ownerAvailability.status,200);
assert.equal(ownerAvailability.data.halls.find(h=>h.id==='t1h0').available,false);
assert.ok(ownerAvailability.data.halls.every(h=>Object.keys(h).sort().join(',')==='available,id,reason'));
const own=mine.bookings[0];
assert.equal((await request(`/availability?date=${own.date}&exclude=${own.id}`,'GET',null,client)).data.halls.find(h=>h.id===own.hallId).available,true);
const someoneElse=all.bookings.find(b=>b.clientId!==mine.clients[0].id&&b.status!=='Cancelled');
assert.equal((await request(`/availability?date=${someoneElse.date}&exclude=${someoneElse.id}`,'GET',null,client)).data.halls.find(h=>h.id===someoneElse.hallId).available,false);

assert.equal(mine.clients.length,1);assert.equal(mine.staff.length,0);assert.ok(mine.bookings.every(b=>b.clientId===mine.clients[0].id));assert.ok(mine.payments.every(p=>mine.bookings.some(b=>b.id===p.bookingId)));
assert.equal((await request('/halls','POST',{name:'Forbidden'},staff)).status,403);
assert.equal((await request('/payments','POST',{},client)).status,403);
const other=(await request('/auth/login','POST',{email:'willow@gatherhall.demo',password:'Welcome123!'})).cookie;
const otherData=(await request('/data','GET',null,other)).data;
assert.ok(otherData.bookings.every(b=>!all.bookings.some(a=>a.id===b.id)));
assert.ok((await request('/availability?date=2026-09-29','GET',null,other)).data.halls.every(h=>otherData.halls.some(x=>x.id===h.id)));

assert.equal((await request('/bookings/'+all.bookings[0].id,'DELETE',null,other)).status,404);
const hall=(await request('/halls','POST',{name:'API test hall',type:'Indoor',capacity:200,price:10000,status:'Available'},owner)).data;
assert.ok(hall.id);
await request('/halls/'+hall.id,'PUT',{...hall,status:'Maintenance'},owner);
assert.equal((await request('/availability?date=2026-12-30','GET',null,owner)).data.halls.find(h=>h.id===hall.id).available,false);
await request('/halls/'+hall.id,'PUT',hall,owner);

const customer=(await request('/clients','POST',{name:'API test client',email:'test@example.com',phone:'9876543210',status:'Active'},owner)).data;
assert.ok(customer.id);
const draft={name:'API test celebration',hallId:hall.id,clientId:customer.id,date:'2026-12-30',time:'18:00',guests:100,type:'Wedding',status:'Confirmed',total:10000,notes:'Integration test'};
const booking=(await request('/bookings','POST',draft,staff)).data;assert.ok(booking.id);
assert.equal((await request('/bookings','POST',draft,owner)).status,400);
assert.equal((await request('/bookings','POST',{...draft,date:'2026-12-29',guests:250},owner)).status,400);
assert.equal((await request('/bookings','POST',{...draft,date:'2026-12-29',clientId:otherData.clients[0].id},owner)).status,400);
assert.equal((await request('/halls/'+hall.id,'DELETE',null,owner)).status,409);
assert.equal((await request('/bookings/'+booking.id,'PUT',{...booking,name:'Updated celebration'},owner)).data.name,'Updated celebration');
const payment=(await request('/payments','POST',{bookingId:booking.id,amount:5000,date:'2026-09-28',method:'UPI',reference:'TEST'},staff)).data;assert.ok(payment.id);
assert.equal((await request('/payments','POST',{bookingId:booking.id,amount:6000,date:'2026-09-28',method:'UPI'},staff)).status,400);
assert.equal((await request('/payments/'+payment.id,'PUT',{...payment,amount:6000},owner)).data.amount,6000);
assert.equal((await request('/payments/'+payment.id,'DELETE',null,owner)).status,200);
assert.equal((await request('/bookings/'+booking.id,'DELETE',null,owner)).status,200);
assert.equal((await request('/clients/'+customer.id,'DELETE',null,owner)).status,200);
assert.equal((await request('/halls/'+hall.id,'DELETE',null,owner)).status,200);
const member=(await request('/staff','POST',{name:'Test member',email:'member@example.com',position:'Coordinator',status:'Active'},owner)).data;assert.ok(member.id);
assert.equal((await request('/staff/'+member.id,'PUT',{...member,position:'Manager'},owner)).data.position,'Manager');
assert.equal((await request('/staff/'+member.id,'DELETE',null,owner)).status,200);
assert.equal((await request('/settings/profile','PUT',{name:'Rohan Kapoor'},client)).data.name,'Rohan Kapoor');
const after=(await request('/data','GET',null,client)).data;assert.deepEqual(after.clients.map(c=>c.id),mine.clients.map(c=>c.id));
assert.equal((await request('/settings/profile','PUT',{name:'Priya Sharma'},client)).data.name,'Priya Sharma');
const requested=(await request('/bookings','POST',{...draft,name:'Client test request',date:'2026-12-28',clientId:mine.clients[0].id,hallId:mine.halls[0].id,total:1,status:'Confirmed'},client)).data;
assert.ok(requested.id);assert.equal(requested.status,'Pending');assert.equal(requested.total,mine.halls[0].price);
await request('/bookings/'+requested.id,'DELETE',null,owner);
await request('/auth/logout','POST',null,client);assert.equal((await request('/data','GET',null,client)).status,401);
const accessContact=(await request('/clients','POST',{name:'Access test',email:'access-test@example.com',phone:'9876543210',status:'Active',loginPassword:'Testing123!'},owner)).data;assert.ok(accessContact.id);
const accessLogin=await request('/auth/login','POST',{email:'access-test@example.com',password:'Testing123!'});assert.equal(accessLogin.status,200);
const accessData=(await request('/data','GET',null,accessLogin.cookie)).data;assert.equal(accessData.clients[0].id,accessContact.id);assert.equal(accessData.bookings.length,0);
assert.equal((await request('/clients/'+accessContact.id,'PUT',{...accessContact,loginPassword:'Testing123!'},owner)).status,400);
assert.equal((await request('/data','GET',null,owner)).status,200);
await request('/clients/'+accessContact.id,'PUT',{...accessContact,status:'Inactive'},owner);
assert.equal((await request('/data','GET',null,accessLogin.cookie)).status,403);
assert.equal((await request('/auth/login','POST',{email:'access-test@example.com',password:'Testing123!'})).status,403);
await request('/clients/'+accessContact.id,'DELETE',null,owner);
assert.equal((await request('/data','GET',null,accessLogin.cookie)).status,401);
console.log('PASS: authentication, tenant isolation, client ownership, role permissions, full CRUD, private availability checks, booking conflicts, capacity, payment balance, account provisioning, account deactivation/deletion, and logout.');
