import assert from 'node:assert/strict';
import { priceBooking } from '../shared/booking-pricing.js';
import { bookingDuration, bookingsOverlap, occupiesDate, matchesDateRange } from '../shared/booking-duration.js';
import { renderConfirmation } from '../shared/confirmation.js';
const hall={id:'h',capacity:500,price:50000,morningPrice:50000,afternoonPrice:60000,eveningPrice:75000};
const plan={id:'p',name:'Test model',mode:'plate',status:'Active',minimumPlates:0,vegRate:650,jainRate:650,nonVegRate:900,mixedRate:800,taxRate:0,advancePercent:30};
const input={planId:'p',pricingVersion:2,plateType:'Vegetarian',guests:150,date:'2026-12-01',time:'18:00',type:'Wedding',hallId:'h'};
const quote=(changes={},model={},venue={})=>priceBooking({...input,...changes},{plans:[{...plan,...model}],hall:{...hall,...venue}});
assert.equal(quote({guaranteedPlates:150,actualGuests:130}).total,97500);
assert.equal(quote({guests:100},{mode:'venue'},{price:120000,capacity:100}).total,120000);
assert.equal(quote({actualGuests:120},{mode:'combined'}).total,128000);
assert.equal(quote({actualGuests:120,guaranteedPlates:150},{mode:'combined'}).total,147500);
assert.equal(quote({actualGuests:80},{minimumPlates:100}).total,65000);
assert.equal(quote({actualGuests:180},{minimumPlates:100}).total,117000);
assert.equal(quote({guests:60},{mode:'venue'},{price:120000,capacity:100}).total,120000);
assert.throws(()=>quote({guests:120},{mode:'venue'},{capacity:100}),/Guest count/);
assert.equal(quote({guests:100},{minimumFoodValue:100000}).total,100000);
assert.equal(quote({guests:180},{minimumFoodValue:100000}).total,117000);
assert.equal(quote({actualGuests:100},{mode:'combined',minimumPlates:150},{price:80000}).total,177500);
assert.equal(quote({actualGuests:200},{mode:'combined',minimumPlates:150},{price:80000}).total,210000);
assert.equal(quote({durationMode:'morning'},{mode:'venue'},{price:120000}).total,50000);
assert.equal(quote({durationMode:'evening'},{mode:'venue'},{price:120000}).total,75000);
assert.equal(quote({durationMode:'full'},{mode:'venue'},{price:120000}).total,120000);
assert.equal(quote({durationMode:'multiple',endDate:'2026-12-03'},{mode:'venue'},{price:120000}).total,360000);
assert.equal(quote({type:'Seminar'},{mode:'venue',eventRates:[{eventType:'Seminar',venueRate:70000}]}).total,70000);
assert.equal(quote({type:'Seminar'},{vegRate:900,eventRates:[{eventType:'Seminar',vegRate:650}]}).total,97500);
const addons=[{id:'a',name:'Decoration',price:40000,unit:'per event',status:'Active'},{id:'b',name:'Projector',price:5000,unit:'per event',status:'Active'},{id:'c',name:'Generator',price:8000,unit:'per event',status:'Active'}];
assert.equal(priceBooking({...input,addOns:addons.map(a=>({id:a.id,quantity:1}))},{plans:[{...plan,mode:'combined'}],hall:{...hall,price:120000},addons}).total,270500);
const guestService={id:'g',name:'Refreshment',price:10,unit:'per guest',status:'Active'};
const synced=priceBooking({...input,guests:150,actualGuests:80,addOns:[{id:'g',quantity:999,quantityMode:'guests'}]},{plans:[{...plan,minimumPlates:100}],hall,addons:[guestService]});
assert.equal(synced.billedPlates,100);assert.equal(synced.addonLines[0].quantity,80);assert.equal(synced.total,65800);
assert.equal(quote({actualGuests:0}).total,0);assert.equal(quote({actualGuests:''}).total,97500);
assert.throws(()=>quote({actualGuests:-1}),/Actual served/);assert.throws(()=>quote({guaranteedPlates:99},{minimumPlates:100}),/Minimum guaranteed/);
const zeroRent=quote({},{mode:'combined',venueRate:0});assert.equal(zeroRent.venueAmount,0);
const day={date:'2026-12-01'},morning={...day,durationMode:'morning'},afternoon={...day,durationMode:'afternoon'},evening={...day,durationMode:'evening'};
assert.equal(bookingsOverlap(morning,afternoon),false);assert.equal(bookingsOverlap(afternoon,evening),true);assert.equal(bookingsOverlap(day,evening),true);
const multi={...day,durationMode:'multiple',endDate:'2026-12-03'};assert.ok(occupiesDate(multi,'2026-12-02'));assert.ok(!occupiesDate(multi,'2026-12-04'));assert.ok(matchesDateRange(multi,'2026-12-02','2026-12-02'));assert.ok(!matchesDateRange(multi,'2026-12-04',''));
const custom={...day,durationMode:'custom',time:'22:00',endDate:'2026-12-02',bookingEndTime:'02:00'};
assert.equal(bookingDuration(custom).rentalUnits,2);assert.ok(bookingsOverlap(custom,{date:'2026-12-02'}));
assert.equal(bookingDuration({...custom,bookingEndTime:'00:00'}).rentalUnits,1);
for(const invalid of [{...custom,endDate:day.date},{...multi,endDate:'2027-01-02'},{date:'2026-02-30'},{...day,durationMode:'unknown'}])assert.throws(()=>bookingDuration(invalid));
// Snapshot catalog/venue rules survive edits; event and duration quantities may change explicitly.
const previous={...input,quote:quote({},{mode:'combined'}),total:147500};
const saved=priceBooking({...input,guests:200},{previous,plans:[{...plan,vegRate:9000}],hall:{...hall,price:999999}});assert.equal(saved.plateRate,650);assert.equal(saved.venueRate,50000);assert.equal(saved.total,180000);
const report=renderConfirmation({booking:{...input,name:'Test',status:'Confirmed',quote:quote({guests:100},{minimumFoodValue:100000}),total:100000},organization:'Venue'});assert.ok(report.includes('Minimum food bill adjustment'));assert.ok(report.includes('₹35,000.00'));assert.ok(report.includes('Reserved duration'));
console.log('PASS pricing cases: MG, actual/expected, rental, rental+catering, capacity, minimum spend, duration, event rates, extras, guest sync and saved agreements.');

const base=process.env.TEST_URL||'http://localhost:3000/api',cleanup=[];
async function req(path,method='GET',body,cookie){const r=await fetch(base+path,{method,headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});const text=await r.text();return {status:r.status,data:r.headers.get('content-type')?.includes('application/json')?JSON.parse(text):text,cookie:r.headers.get('set-cookie')?.split(';')[0]};}
const owner=(await req('/auth/login','POST',{email:'owner@gatherhall.demo',password:'Welcome123!'})).cookie;
const client=(await req('/auth/login','POST',{email:'client@gatherhall.demo',password:'Welcome123!'})).cookie;
async function add(kind,body){const r=await req('/'+kind,'POST',body,owner);assert.equal(r.status,201,JSON.stringify(r.data));cleanup.push([kind,r.data.id]);return r.data;}
try{
 const data=(await req('/data','GET',null,owner)).data;
 const venue=await add('halls',{name:'Duration test hall',type:'Indoor',capacity:500,price:120000,morningPrice:50000,afternoonPrice:60000,eveningPrice:75000,status:'Available'});
 const model=await add('pricing-models',{...plan,name:'Flow test model',minimumPlates:100,minimumFoodValue:100000,eventRates:[{eventType:'Seminar',vegRate:800}]});
 const draft={...input,name:'Flow test event',clientId:data.clients[0].id,hallId:venue.id,planId:model.id,status:'Confirmed',durationMode:'morning',guaranteedPlates:100};
 let booking=await add('bookings',draft);assert.equal(booking.total,100000);assert.equal(booking.quote.billedPlates,150);assert.equal(booking.quote.minimumFoodTopUp,2500);
 assert.equal((await req('/bookings','POST',{...draft,status:'Cancelled'},client)).status,400);
 const later=await add('bookings',{...draft,name:'Afternoon event',durationMode:'afternoon'});
 assert.equal((await req('/bookings','POST',{...draft,durationMode:'evening'},owner)).status,400);
 assert.equal((await req('/bookings','POST',{...draft,durationMode:'full'},owner)).status,400);
 const check=await req('/availability?'+new URLSearchParams({date:draft.date,durationMode:'morning',exclude:booking.id}),'GET',null,owner);assert.equal(check.data.halls.find(h=>h.id===venue.id).available,true);
 const oldTotal=booking.total;
 booking=(await req('/bookings/'+booking.id,'PUT',{...booking,actualGuests:180},owner)).data;assert.equal(booking.total,117000);assert.equal(booking.actualGuests,180);assert.equal(booking.pricingVersion,2);
 booking=(await req('/bookings/'+booking.id,'PUT',{...booking,pricingVersion:1,guests:190},owner)).data;assert.equal(booking.pricingVersion,2);assert.equal(booking.total,117000);
 const html=await req('/bookings/'+booking.id+'/confirmation','GET',null,owner);assert.ok(html.data.includes('₹1,17,000.00'));assert.ok(html.data.includes('Actual served recorded'));assert.ok(html.data.includes('Morning'));
 await add('payments',{bookingId:booking.id,amount:110000,date:'2026-09-28',method:'UPI'});
 assert.equal((await req('/bookings/'+booking.id,'PUT',{...booking,actualGuests:80},owner)).status,400);
 const multiBooking=await add('bookings',{...draft,date:'2026-12-05',durationMode:'multiple',endDate:'2026-12-07'});
 assert.equal((await req('/bookings','POST',{...draft,date:'2026-12-06'},owner)).status,400);
 assert.equal((await req('/availability?date=2026-12-07&durationMode=evening','GET',null,client)).data.halls.find(h=>h.id===venue.id).available,false);
 const request=await req('/bookings','POST',{...draft,pricingVersion:1,date:'2026-12-08',guests:200,actualGuests:0,total:1,discount:100000,quote:{total:1}},client);
 assert.equal(request.status,201,JSON.stringify(request.data));cleanup.push(['bookings',request.data.id]);assert.equal(request.data.actualGuests,null);assert.equal(request.data.total,130000);assert.equal(request.data.status,'Pending');
 for(const changes of [{minimumFoodValue:-1},{eventRates:[{eventType:'Invalid',vegRate:20}]},{eventRates:[{eventType:'Wedding'},{eventType:'Wedding'}]},{venueRate:-1}])assert.equal((await req('/pricing-models/'+model.id,'PUT',{...model,...changes},owner)).status,400);
 const rental=await add('pricing-models',{...plan,mode:'venue',name:'Rental flow model'});
 const rentalBooking=await add('bookings',{...draft,planId:rental.id,date:'2026-12-10',durationMode:'multiple',endDate:'2026-12-12'});assert.equal(rentalBooking.total,360000);
 await req('/halls/'+venue.id,'PUT',{...venue,price:999999},owner);
 const edited=(await req('/bookings/'+rentalBooking.id,'PUT',{...rentalBooking,endDate:'2026-12-13'},owner)).data;assert.equal(edited.total,480000);
 console.log('PASS booking flow API: shift conflicts, multiday overlap, authoritative actual/expected billing, client restrictions, payment protection, printable totals and locked rental rates.');
}finally{for(const [kind,id] of cleanup.reverse())await req('/'+kind+'/'+id,'DELETE',null,owner);}
