import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {randomBytes} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
import {encryptConfig,decryptConfig,validateConfig,sendProvider,encryptionReady} from '../server/integrations.js';
process.env.INTEGRATION_ENCRYPTION_KEY=randomBytes(32).toString('base64');
assert(encryptionReady());
assert.throws(()=>validateConfig('razorpay',{keyId:'login@example.test'},false),/not your login email/);
const encrypted=encryptConfig('email',{password:'not-a-real-secret'});
assert(!encrypted.includes('not-a-real-secret'));assert.equal(decryptConfig('email',encrypted).password,'not-a-real-secret');
assert.throws(()=>decryptConfig('sms',encrypted));const altered=Buffer.from(encrypted,'base64');altered[30]^=1;assert.throws(()=>decryptConfig('email',altered.toString('base64')));
assert.throws(()=>validateConfig('email',{host:'localhost',port:'25',user:'x',password:'x',from:'test@example.test'},true));
assert.throws(()=>validateConfig('whatsapp',{token:'x',phoneId:'../../',template:'bad name',language:'en'},true));
assert.throws(()=>validateConfig('sms',{},true));
assert.throws(()=>validateConfig('sms',{authKey:'x',flowId:'approvedflow',approved:'false'},true),/Confirm provider template approval/);
assert.equal(validateConfig('sms',{authKey:'x',flowId:'approvedflow',approved:'true'},true).approved,'true');
const originalFetch=global.fetch;
try{global.fetch=async()=>new Response(JSON.stringify({messages:[{id:'provider-1'}]}),{status:200});assert.equal((await sendProvider('whatsapp',{phoneId:'123',token:'x',template:'booking',language:'en'},'+919999999999','hello')).outcome,'sent');global.fetch=async()=>new Response('{}',{status:400});assert.equal((await sendProvider('whatsapp',{},'+919999999999','hello')).outcome,'failed');global.fetch=async()=>new Response('{}',{status:200});assert.equal((await sendProvider('whatsapp',{},'+919999999999','hello')).outcome,'unknown');assert.equal((await sendProvider('sms',{},'+919999999999','hello')).outcome,'unknown');global.fetch=async()=>new Response(JSON.stringify({type:'error'}),{status:200});assert.equal((await sendProvider('sms',{},'+919999999999','hello')).outcome,'failed');global.fetch=async()=>{throw Error('timeout');};assert.equal((await sendProvider('sms',{},'+919999999999','hello')).outcome,'unknown');}finally{global.fetch=originalFetch;}
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,raw_user_meta_data jsonb default '{}');create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;create function auth.jwt() returns jsonb language sql as $$select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$;grant usage on schema auth to anon,authenticated,service_role;grant execute on function auth.uid(),auth.jwt() to anon,authenticated,service_role;`);
for(const file of (await readdir('supabase/migrations')).filter(f=>f.endsWith('.sql')).sort())await db.exec(await readFile('supabase/migrations/'+file,'utf8'));
const uid='00000000-0000-4000-8000-000000000001',other='00000000-0000-4000-8000-000000000002';
await db.query("insert into auth.users(id,email,email_confirmed_at) values($1,'owner@example.test',now()),($2,'other@example.test',now())",[uid,other]);
const plan=(await db.query("update public.saas_plans set published=true where name='Starter' returning id")).rows[0];
const t=(await db.query('select public.saas_register_org($1,$2) as id',[uid,{name:'First venue',planId:plan.id,interval:'monthly'}])).rows[0].id;
const t2=(await db.query('select public.saas_register_org($1,$2) as id',[other,{name:'Other venue',planId:plan.id,interval:'monthly'}])).rows[0].id;
const scalar=async(sql,args=[])=>(await db.query(sql,args)).rows[0]?.v;
const summary=()=>scalar('select public.message_summary($1) v',[t]);
await db.query("insert into public.saas_records(id,tenant_id,kind,body) values('b1',$1,'bookings','{\"status\":\"Confirmed\"}')",[t]);
assert.equal(await scalar('select count(*)::int v from public.message_jobs'),0,'disabled by default');
await db.query("insert into public.message_preferences values($1,'{\"email\":true,\"sms\":true}',true,true)",[t]);
await db.query("insert into public.saas_records(id,tenant_id,kind,body) values('b2',$1,'bookings','{\"status\":\"Pending\"}')",[t]);
await db.query("update public.saas_records set body='{\"status\":\"Confirmed\"}' where id='b2'");
assert.equal(await scalar('select count(*)::int v from public.message_jobs'),4);
await db.query("update public.saas_records set body='{\"status\":\"Cancelled\"}' where id='b2'");
await db.query("update public.saas_records set body='{\"status\":\"Confirmed\"}' where id='b2'");
assert.equal(await scalar('select count(*)::int v from public.message_jobs'),4,'no duplicate confirmation jobs');
await db.query("select public.message_grant($1,'email',2,'grant1','Referral reward',null)",[t]);
await db.query("select public.message_grant($1,'email',2,'grant1','Referral reward',null)",[t]);
await db.query("select public.message_grant($1,'email',99,'expired','Expired',now()-interval '1 day')",[t]);
await db.query("select public.message_grant($1,'email',99,'other','Other tenant',null)",[t2]);
assert.equal((await summary()).balances.email,2);
const jobs=(await db.query("select * from public.message_jobs where channel='email' order by id")).rows;
for(const j of jobs)await db.query("update public.message_jobs set status='processing' where id=$1",[j.id]);
assert.equal(await scalar('select public.message_reserve($1) v',[jobs[0].id]),true);
assert.equal(await scalar('select public.message_reserve($1) v',[jobs[0].id]),false,'double reservation rejected');
assert.equal((await summary()).balances.email,1);
await db.query("select public.message_finish($1,'failed','Rejected',null)",[jobs[0].id]);
await db.query("select public.message_finish($1,'failed','Rejected',null)",[jobs[0].id]);
assert.equal((await summary()).balances.email,2,'release idempotent');
await db.query('select public.message_reserve($1)',[jobs[1].id]);
await db.query("select public.message_finish($1,'unknown','Timeout',null)",[jobs[1].id]);
assert.equal((await summary()).balances.email,1,'uncertain outcomes keep reservation');
await assert.rejects(db.query("select public.message_reconcile($1,false,'Provider log confirms failure',$2)",[jobs[1].id,uid]),/Administrator/);
await db.query('insert into public.platform_admins values($1)',[uid]);
await db.query("select public.message_reconcile($1,true,'Provider log confirms acceptance',$2)",[jobs[1].id,uid]);
assert.equal((await summary()).charged.email,1);
await assert.rejects(db.query("select public.message_reconcile($1,true,'Repeat reconciliation',$2)",[jobs[1].id,uid]),/Only uncertain/);
const sms=(await db.query("select * from public.message_jobs where channel='sms' limit 1")).rows[0];
await db.query("update public.message_jobs set status='processing' where id=$1",[sms.id]);
assert.equal(await scalar('select public.message_reserve($1) v',[sms.id]),false,'no cross-channel balance');
await db.query("select public.message_finish($1,'held','No balance',null)",[sms.id]);
await db.query("insert into public.message_orders(tenant_id,pack,provider_order_id,status) values($1,'{\"channel\":\"sms\",\"credits\":50,\"price_paise\":10000}','order_test','pending')",[t]);
await assert.rejects(db.query("select public.message_recharge('order_test','pay_test',100)"),/amount mismatch/);
await db.query("select public.message_recharge('order_test','pay_test',10000)");
await db.query("select public.message_recharge('order_test','pay_test',10000)");
assert.equal((await summary()).balances.sms,50,'recharge credits exactly once');
await db.query("insert into public.message_allowances values('plan',$1,'whatsapp',30,false),('organization',$2,'whatsapp',7,true)",[plan.id,t]);
await db.query("update public.saas_subscriptions set paid_through=now()+interval '30 days' where tenant_id=$1",[t]);
for(const id of ['pay_cycle1','pay_cycle_duplicate'])await db.query("insert into public.billing_payments values($1,$2,10000,'INR',now(),now())",[id,t]);
assert.equal((await summary()).balances.whatsapp,7,'organization override, one grant per paid period');
assert.equal(await scalar("select expires_at is null v from public.message_grants where channel='whatsapp'"),true,'rollover does not expire');
await db.query("update public.message_allowances set rollover=false,credits=3 where scope='organization'");
await db.query("update public.saas_subscriptions set paid_through=paid_through+interval '30 days' where tenant_id=$1",[t]);
await db.query("insert into public.billing_payments values('pay_cycle2',$1,10000,'INR',now(),now())",[t]);
assert.equal((await summary()).balances.whatsapp,10);
assert.equal(await scalar("select count(*)::int v from public.message_grants where channel='whatsapp' and expires_at is not null"),1);
await db.exec('set role authenticated');
for(const table of ['platform_integrations','message_grants','message_jobs','message_consents','message_orders'])await assert.rejects(db.query('select * from public.'+table),/permission denied/);
await assert.rejects(db.query('select public.message_summary(null)'),/permission denied/);
await assert.rejects(db.query("select public.message_grant($1,'email',9999,'hack','hack',null)",[t]),/permission denied/);
await db.exec('reset role');await db.close();
console.log('PASS messaging: encrypted secrets, tamper/AAD checks, provider outcomes, outbox idempotency, atomic reservation/release, uncertain reconciliation, recharge deduplication, expiry/rollover, individual allowances and denied browser access. No live providers used.');
