import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {verifyCheckout,verifyWebhook,entitlement,billingMetrics,publicPlan} from '../server/saas-core.js';
const secret='test-only-secret',sig=createHmac('sha256',secret).update('pay_1|sub_1').digest('hex');
assert(verifyCheckout('pay_1','sub_1',sig,secret));
assert(!verifyCheckout('pay_1','sub_2',sig,secret));
for(const signature of ['',undefined,'é'.repeat(64),'0'.repeat(63),'z'.repeat(64)])assert(!verifyCheckout('pay_1','sub_1',signature,secret));
const raw=Buffer.from('{"event":"subscription.charged"}');
const h=createHmac('sha256',secret).update(raw).digest('hex');assert(verifyWebhook(raw,h,secret));assert(!verifyWebhook(Buffer.from(raw.toString()+' '),h,secret));
const now=Date.now(),future=new Date(now+3600000).toISOString(),past=new Date(now-3600000).toISOString();
assert(entitlement({status:'active'},{status:'trialing',trial_until:future},now).active);
assert(!entitlement({status:'active'},{status:'trialing',trial_until:past},now).active);
assert(!entitlement({status:'suspended'},{paid_through:future},now).active);
assert(!entitlement({status:'active'},{status:'authenticated'},now).active);
assert(entitlement({status:'active'},{status:'cancelled',paid_through:future},now).active);
assert(entitlement({status:'active'},{status:'authenticated',trial_until:future},now).active);
assert(!entitlement({status:'active'},{status:'pending',trial_until:past},now).active);
assert(entitlement({status:'suspended'},{paid_through:future},now).readOnly);
assert.equal(billingMetrics([], [{status:'authenticated',trial_until:future}], [], now).trials,1);
assert.equal(billingMetrics([], [{status:'active',paid_through:future,trial_until:future,interval:'monthly',plan_snapshot:{monthly_paise:100}}], [], now).trials,0);
const m=billingMetrics([{status:'active'}],[{interval:'yearly',plan_snapshot:{yearly_paise:120000},paid_through:future}],[{amount_paise:120000}],now);assert.equal(m.mrrPaise,10000);assert.equal(m.grossCollectedPaise,120000);
assert(!('secret' in publicPlan({secret:'hidden'})));
console.log('PASS SaaS core: checkout binding, raw webhook signatures, malformed signatures, entitlement expiry/suspension and estimated billing metrics.');
