import {z} from 'zod';
import {pageSlugs} from '../shared/marketing-content.js';
export const cmsDocument=z.object({title:z.string().trim().min(1).max(180),summary:z.string().trim().max(600),body:z.string().trim().max(30000),cta_label:z.string().trim().max(60),seo_title:z.string().trim().max(180),seo_description:z.string().trim().max(320),category:z.string().trim().max(80)});
export const cmsSave=z.object({id:z.string().uuid().optional(),revision:z.number().int().positive().optional(),kind:z.enum(['page','blog']),slug:z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(100),locale:z.enum(['en','hi']),draft:cmsDocument}).superRefine((p,ctx)=>{if(p.kind==='page'&&!pageSlugs.includes(p.slug))ctx.addIssue({code:'custom',message:'Choose a supported website page.'});if(p.id&&!p.revision)ctx.addIssue({code:'custom',message:'Reload the current revision before saving.'});});
export const cmsAction=z.object({id:z.string().uuid(),revision:z.number().int().positive(),action:z.enum(['publish','unpublish','delete','restore']),historyId:z.string().uuid().optional()}).superRefine((p,ctx)=>{if(p.action==='restore'&&!p.historyId)ctx.addIssue({code:'custom',message:'Choose a saved revision.'});});
export const enquirySchema=z.object({name:z.string().trim().min(2).max(120),email:z.string().trim().email().max(254),organization:z.string().trim().max(120).default(''),message:z.string().trim().min(10).max(3000),locale:z.enum(['en','hi']),consent:z.literal(true),website:z.string().max(300).default(''),policyId:z.string().uuid(),policyRevision:z.number().int().positive()});
export function installPublicCMS(app,{admin,result,rpc,route,rateLimit}){
 app.get('/api/public/content',route(async(req,res)=>{const locale=z.enum(['en','hi']).parse(req.query.locale||'en');const entries=[];for(let offset=0;;offset+=1000){const batch=await result(admin.from('cms_entries').select('id,kind,slug,locale,published,published_at,published_revision').eq('locale',locale).not('published','is',null).order('published_at',{ascending:false}).order('id').range(offset,offset+999));entries.push(...batch);if(batch.length<1000)break;}res.json(entries.map(entry=>({id:entry.id,kind:entry.kind,slug:entry.slug,locale:entry.locale,content:entry.published,published_at:entry.published_at,published_revision:entry.published_revision})));}));
 app.post('/api/public/enquiries',rateLimit('website-enquiry',5,900),route(async(req,res)=>{const p=enquirySchema.parse(req.body);if(!p.website)await rpc('saas_cms_enquiry',{p});res.status(201).json({received:true});}));
}
export function installPlatformCMS(app,{admin,result,rpc,route,platform}){
 app.get('/api/platform/cms',platform,route(async(_req,res)=>{const entries=[];for(let offset=0;;offset+=1000){const batch=await result(admin.from('cms_entries').select('*').order('id').range(offset,offset+999));entries.push(...batch);if(batch.length<1000)break;}res.json(entries);}));
 app.post('/api/platform/cms/save',platform,route(async(req,res)=>res.json(await rpc('saas_cms_write',{actor:req.actor.id,action:'save',p:cmsSave.parse(req.body)}))));
 app.post('/api/platform/cms/action',platform,route(async(req,res)=>{const p=cmsAction.parse(req.body);res.json(await rpc('saas_cms_write',{actor:req.actor.id,action:p.action,p}));}));
 app.get('/api/platform/cms/:id/history',platform,route(async(req,res)=>{const id=z.string().uuid().parse(req.params.id);res.json(await result(admin.from('cms_history').select('*').eq('entry_id',id).order('created_at',{ascending:false}).limit(30)));}));
 app.get('/api/platform/enquiries',platform,route(async(_req,res)=>res.json(await result(admin.from('cms_enquiries').select('*').order('created_at',{ascending:false}).limit(100)))));
 app.post('/api/platform/enquiries/action',platform,route(async(req,res)=>{const p=z.object({id:z.string().uuid(),action:z.enum(['read','closed','delete'])}).parse(req.body);res.json(await rpc('saas_cms_enquiry_action',{actor:req.actor.id,p}));}));
}
