import express from 'express';
import {z} from 'zod';
import {randomUUID} from 'node:crypto';
import {channels} from '../shared/integrations.js';
import {readIntegration,sendProvider} from './integrations.js';
import {entitlement,verifyWebhook} from './saas-core.js';
const channel=z.enum(channels),uuid=z.string().uuid(),count=z.number().int().min(1).max(1000000);
const failure=(message,status=400)=>Object.assign(Error(message),{status});
export function installRechargeWebhook(app,{admin,result,rpc,route,razor}){
 app.post('/api/webhooks/credits',express.raw({type:'application/json',limit:'256kb'}),route(async(req,res)=>{
  if(!process.env.RAZORPAY_WEBHOOK_SECRET||!Buffer.isBuffer(req.body)||!verifyWebhook(req.body,req.get('x-razorpay-signature'),process.env.RAZORPAY_WEBHOOK_SECRET))throw failure('Invalid webhook signature.',401);
  const event=JSON.parse(req.body.toString());if(event.event==='payment.captured'){const payment=event.payload?.payment?.entity;if(payment?.order_id){const order=await result(admin.from('message_orders').select('id').eq('provider_order_id',payment.order_id).maybeSingle());if(order)await verifyRecharge(payment.id,{razor,rpc});}}
  res.json({received:true});
 }));
}
async function verifyRecharge(id,{razor,rpc},expectedOrder){if(!/^pay_[a-zA-Z0-9]+$/.test(id))throw failure('Invalid payment reference.');const p=await razor('payments/'+id);if(p.status!=='captured'||p.currency!=='INR'||!p.order_id||(expectedOrder&&p.order_id!==expectedOrder))throw failure('Payment is not captured for this recharge. Try verification after capture.',409);await rpc('message_recharge',{oid:p.order_id,pid:p.id,amount:p.amount});}
export function installMessaging(app,deps){
 const {admin,result,rpc,route,platform,owner,member,rateLimit,razor}=deps;
 const audit=async(req,action,details,t=null)=>result(admin.from('audit_log').insert({actor_id:req.actor.id,tenant_id:t,action,details}));
 for(const isPlatform of [true,false]){
  const prefix=isPlatform?'/api/platform/messages':'/api/messages',guards=isPlatform?[platform]:[owner,member];
  app.get(prefix,...guards,route(async(req,res)=>{
   const t=isPlatform?(req.query.tenant?uuid.parse(req.query.tenant):null):req.organization.id;
   const scoped=(table,columns='*')=>{const q=admin.from(table).select(columns);return t?q.eq('tenant_id',t):q;};
   const [summary,jobs,events,packs,grants,orders]=await Promise.all([rpc('message_summary',{t}),result(scoped('message_jobs').order('created_at',{ascending:false}).limit(100)),result(scoped('message_credit_events').order('id',{ascending:false}).limit(100)),result(isPlatform?admin.from('message_packs').select('*'):admin.from('message_packs').select('*').eq('active',true)),result(scoped('message_grants').order('created_at',{ascending:false}).limit(100)),result(scoped('message_orders').order('created_at',{ascending:false}).limit(30))]);
   let extra={};if(isPlatform){extra={organizations:await result(admin.from('organizations').select('id,name').order('name').limit(1000)),plans:await result(admin.from('saas_plans').select('id,name').order('name')),allowances:await result(admin.from('message_allowances').select('*'))};}else{extra={preferences:await result(admin.from('message_preferences').select('*').eq('tenant_id',t).maybeSingle()),consents:await result(scoped('message_consents').order('updated_at',{ascending:false}).limit(1000)),clients:await result(admin.from('saas_records').select('id,body').eq('tenant_id',t).eq('kind','clients').order('id').limit(1000))};}
   res.json({summary,jobs,events,packs,grants,orders,...extra,workerEnabled:process.env.MESSAGE_WORKER_ENABLED==='true'});
  }));
  app.post(prefix+'/retry',...guards,rateLimit('message-retry',30,900),route(async(req,res)=>{const id=uuid.parse(req.body.id);let q=admin.from('message_jobs').update({status:'queued',reason:'',updated_at:new Date().toISOString()}).eq('id',id).eq('status','held').is('grant_id',null);if(!isPlatform)q=q.eq('tenant_id',req.organization.id);const changed=await result(q.select('id'));if(!changed.length)throw failure('Only held, uncharged messages can be retried.',409);await audit(req,'message.retry',{id},isPlatform?null:req.organization.id);res.json({queued:true});}));
 }
 app.post('/api/messages/preferences',owner,member,route(async(req,res)=>{const p=z.object({channels:z.object({email:z.boolean(),sms:z.boolean(),whatsapp:z.boolean()}),owner_alerts:z.boolean(),customer_alerts:z.boolean()}).parse(req.body);await result(admin.from('message_preferences').upsert({...p,tenant_id:req.organization.id}));await audit(req,'messages.preferences',p,req.organization.id);res.json({saved:true});}));
 app.post('/api/messages/consent',owner,member,route(async(req,res)=>{const p=z.object({client_id:z.string().min(1).max(100),channel,allowed:z.boolean(),evidence:z.string().trim().min(5).max(500)}).parse(req.body);const client=await result(admin.from('saas_records').select('body').eq('tenant_id',req.organization.id).eq('id',p.client_id).eq('kind','clients').single());const destination=String(client.body[p.channel==='email'?'email':'phone']||'').trim();if(p.allowed)validateDestination(p.channel,destination);await result(admin.from('message_consents').upsert({...p,destination,tenant_id:req.organization.id,actor_id:req.actor.id,updated_at:new Date().toISOString()}));await audit(req,'messages.consent',{client_id:p.client_id,channel:p.channel,allowed:p.allowed,evidence:p.evidence,destination},req.organization.id);res.json({saved:true});}));
 app.post('/api/platform/messages/reconcile',platform,rateLimit('message-reconcile',20,900),route(async(req,res)=>{const p=z.object({id:uuid,accepted:z.boolean(),evidence:z.string().trim().min(10).max(500)}).parse(req.body);await rpc('message_reconcile',{jid:p.id,accepted:p.accepted,evidence:p.evidence,actor:req.actor.id});res.json({saved:true});}));
 app.post('/api/platform/messages/reconcile-order',platform,rateLimit('credit-reconcile',10,900),route(async(req,res)=>{const p=z.object({id:uuid,orderId:z.string().regex(/^order_[a-zA-Z0-9]+$/)}).parse(req.body),o=await result(admin.from('message_orders').select('*').eq('id',p.id).single());if(o.status!=='creating')throw failure('Only uncertain order creation may be reconciled.',409);const order=await razor('orders/'+p.orderId);if(order.receipt!==o.id||order.notes?.credit_order_id!==o.id||order.currency!=='INR'||Number(order.amount)!==Number(o.pack.price_paise))throw failure('Provider order does not match the recharge snapshot.',409);await result(admin.from('message_orders').update({provider_order_id:order.id,status:'pending'}).eq('id',o.id).eq('status','creating'));await audit(req,'messages.order_reconciled',{id:o.id,orderId:order.id},o.tenant_id);const payments=await razor('orders/'+order.id+'/payments');const paid=payments.items?.find(x=>x.status==='captured');if(paid)await verifyRecharge(paid.id,{razor,rpc},order.id);res.json({saved:true});}));
 app.post('/api/platform/messages/pack',platform,route(async(req,res)=>{const p=z.object({id:uuid.optional(),name:z.string().trim().min(2).max(80),channel,credits:count,price_paise:z.number().int().min(100).max(100000000),active:z.boolean()}).parse(req.body);await result(admin.from('message_packs').upsert(p));await audit(req,'messages.pack',p);res.json({saved:true});}));
 app.post('/api/platform/messages/allowance',platform,route(async(req,res)=>{const p=z.object({scope:z.enum(['plan','organization']),scope_id:uuid,channel,credits:count.or(z.literal(0)),rollover:z.boolean()}).parse(req.body);const entity=await result(admin.from(p.scope==='plan'?'saas_plans':'organizations').select('id').eq('id',p.scope_id).single());if(!entity)throw failure('Choose a valid plan or organization.');await result(admin.from('message_allowances').upsert(p));await audit(req,'messages.allowance',p);res.json({saved:true});}));
 app.post('/api/platform/messages/grant',platform,rateLimit('message-grant',30,900),route(async(req,res)=>{const p=z.object({tenant_id:uuid,channel,credits:count,request_id:uuid,reason:z.string().trim().min(5).max(300),expires_at:z.iso.datetime().nullable()}).parse(req.body);if(p.expires_at&&Date.parse(p.expires_at)<=Date.now())throw failure('Expiry must be in the future.');await rpc('message_grant',{t:p.tenant_id,c:p.channel,n:p.credits,src:'manual:'+p.request_id,why:p.reason,expiry:p.expires_at});await audit(req,'messages.grant',{...p},p.tenant_id);res.json({saved:true});}));
 app.post('/api/messages/recharge',owner,member,rateLimit('message-recharge',10,900),route(async(req,res)=>{const packId=uuid.parse(req.body.packId),pack=await result(admin.from('message_packs').select('*').eq('id',packId).eq('active',true).single());if(!pack)throw failure('Credit pack is unavailable.');const id=randomUUID();await result(admin.from('message_orders').insert({id,tenant_id:req.organization.id,pack}));const order=await razor('orders','POST',{amount:pack.price_paise,currency:'INR',receipt:id,notes:{credit_order_id:id}});await result(admin.from('message_orders').update({provider_order_id:order.id,status:'pending'}).eq('id',id));res.json({id,order_id:order.id,key:process.env.RAZORPAY_KEY_ID,amount:pack.price_paise,currency:'INR',name:'Gatherhall credits',description:pack.name});}));
 app.post('/api/messages/recharge/verify',owner,member,rateLimit('recharge-verify',20,900),route(async(req,res)=>{const p=z.object({id:uuid,paymentId:z.string()}).parse(req.body);const order=await result(admin.from('message_orders').select('*').eq('id',p.id).eq('tenant_id',req.organization.id).single());if(!order?.provider_order_id)throw failure('Recharge is awaiting reconciliation.',409);await verifyRecharge(p.paymentId,{razor,rpc},order.provider_order_id);res.json({verified:true});}));
 // Server-to-provider reconciliation supports a closed checkout browser without trusting client payment amounts.
 app.post('/api/messages/recharge/refresh',owner,member,rateLimit('recharge-refresh',20,900),route(async(req,res)=>{const id=uuid.parse(req.body.id),o=await result(admin.from('message_orders').select('*').eq('id',id).eq('tenant_id',req.organization.id).single());if(!o?.provider_order_id)throw failure('Order creation is uncertain. Contact support; do not pay again.',409);const p=await razor('orders/'+encodeURIComponent(o.provider_order_id)+'/payments');const paid=p.items?.find(x=>x.status==='captured');if(!paid)throw failure('No captured payment found yet.',409);await verifyRecharge(paid.id,{razor,rpc},o.provider_order_id);res.json({verified:true});}));
}
function validateDestination(channel,to){if(channel==='email')z.email().max(254).parse(to);else z.string().regex(/^\+[1-9]\d{7,14}$/, 'Use international format, for example +919876543210.').parse(to);}
export function startMessageWorker({admin,result,rpc}){
 if(process.env.MESSAGE_WORKER_ENABLED!=='true')return ()=>{};
 let busy=false,stopped=false;
 async function tick(){if(busy||stopped)return;busy=true;try{for(let i=0;i<10&&!stopped;i++){const j=await rpc('message_claim',{});if(!j)break;let reserved=false;const finish=(outcome,why,pid=null)=>rpc('message_finish',{jid:j.id,outcome,why,pid});try{
 const [org,sub,prefs,record,integration]=await Promise.all([result(admin.from('organizations').select('*').eq('id',j.tenant_id).single()),result(admin.from('saas_subscriptions').select('*').eq('tenant_id',j.tenant_id).single()),result(admin.from('message_preferences').select('*').eq('tenant_id',j.tenant_id).maybeSingle()),result(admin.from('saas_records').select('body').eq('id',j.booking_id).eq('tenant_id',j.tenant_id).eq('kind','bookings').maybeSingle()),readIntegration(admin,result,j.channel)]);
 if(!entitlement(org,sub).active){await finish('held','Organization access is inactive.');continue;}
 if(!prefs?.channels[j.channel]||!prefs[j.recipient==='owner'?'owner_alerts':'customer_alerts']){await finish('held','Notifications disabled.');continue;}
 if(!integration?.enabled){await finish('held','Provider is not enabled.');continue;}
 if(!record||record.body.status!=='Confirmed'){await finish('held','Booking is no longer confirmed.');continue;}
 const b=record.body;let to;
 if(j.recipient==='owner')to=org[j.channel==='email'?'billing_email':'phone'];else{const client=await result(admin.from('saas_records').select('body').eq('id',b.clientId).eq('tenant_id',j.tenant_id).eq('kind','clients').maybeSingle()),consent=await result(admin.from('message_consents').select('*').eq('tenant_id',j.tenant_id).eq('client_id',b.clientId).eq('channel',j.channel).maybeSingle());to=client?.body[j.channel==='email'?'email':'phone'];if(client?.body.status!=='Active'||!consent?.allowed||consent.destination!==String(to||'').trim()){await finish('held','Customer consent missing, withdrawn, or contact changed.');continue;}}
 try{to=String(to||'').trim();validateDestination(j.channel,to);}catch{await finish('held','Recipient address is invalid. Use international phone format.');continue;}
 if(!await rpc('message_reserve',{jid:j.id})){await finish('held','Insufficient channel credits.');continue;}reserved=true;
 // Event-only text: never include invoices, balance, operations notes or family contact details.
 const text=`Booking confirmed: ${b.name}. ${b.date} at ${b.time}. Venue: ${b.hall}. ${org.name}.`.replace(/[\r\n\t]/g,' ').slice(0,500);
 const outcome=await sendProvider(j.channel,integration.config,to,text,{event:b.name,date:b.date,time:b.time,venue:b.hall,organization:org.name});await finish(outcome.outcome,outcome.outcome==='sent'?'Accepted by provider; delivery is not confirmed.':outcome.outcome==='failed'?'Provider rejected message; credit released.':'Provider outcome uncertain. Credit reserved; reconcile before any resend.',outcome.id||null);
 }catch{await finish(reserved?'unknown':'held',reserved?'Send outcome uncertain; reconcile with provider.':'Configuration or recipient check failed.').catch(()=>{});}}
 }catch{console.error('Message worker unavailable; check migrations and configuration.');}finally{busy=false;}}
 const timer=setInterval(tick,5000);timer.unref();const stop=()=>{stopped=true;clearInterval(timer);};stop.runOnce=tick;return stop;
}
