import React,{useEffect,useRef} from 'react';
import {Flower2,X,Check,Building2,Users,ShieldCheck,ArrowRight,LoaderCircle} from 'lucide-react';
import {currency} from './api.js';
export function Logo(){return <a className="saas-brand" href="/"><span><Flower2 size={25}/></span>Gatherhall<span className="saas-brand-dot">.</span></a>;}
export function Badge({value}){const key=String(value||'pending').toLowerCase();return <span className={'saas-badge '+key}><i/>{key.replaceAll('_',' ')}</span>;}
export function Notice({children,error=false}){return <div className={'saas-notice '+(error?'error':'')} role={error?'alert':'status'}><ShieldCheck size={17}/><span>{children}</span></div>;}
export function Loading(){return <div className="saas-loading"><Flower2 size={32}/><p>Preparing your workspace…</p></div>;}
export function Modal({title,description,onClose,children}){const ref=useRef(null);useEffect(()=>{const before=document.activeElement,old=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.querySelector('button')?.focus();const handler=e=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const all=[...ref.current.querySelectorAll('button,input,select,textarea,a[href]')].filter(n=>!n.disabled&&n.getClientRects().length);const first=all[0],last=all.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',handler);return()=>{document.removeEventListener('keydown',handler);document.body.style.overflow=old;before?.focus();};},[]);return <div className="saas-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section ref={ref} className="saas-modal" role="dialog" aria-modal="true" aria-labelledby="saas-modal-title"><header><div><h2 id="saas-modal-title">{title}</h2>{description&&<p>{description}</p>}</div><button className="saas-icon" aria-label="Close dialog" onClick={onClose}><X size={20}/></button></header>{children}</section></div>;}
export function PlanCards({plans,interval='monthly',onChoose,selectedId,preview=false}){return <div className="saas-plan-grid">{plans.map((plan,i)=><article className={'saas-plan '+(selectedId===plan.id?'chosen':'')+(i===1?' featured':'')} key={plan.id}>{i===1&&<div className="saas-plan-ribbon">ROOM TO GROW</div>}<div className="saas-plan-icon"><Building2 size={22}/></div><h3>{plan.name}</h3><p>{plan.description}</p><div className="saas-plan-price">{currency(plan[interval==='yearly'?'yearly_paise':'monthly_paise'])}<small>/{interval==='yearly'?'year':'month'}</small></div><span className="saas-plan-trial">{plan.trial_days?`${plan.trial_days}-day trial · no automatic charge during trial`:'Paid activation required'}</span><ul><li><Check size={15}/>{plan.max_halls} marriage {plan.max_halls===1?'hall':'halls'}</li><li><Check size={15}/>Up to {plan.max_staff} active team members</li><li><Check size={15}/>Bookings, menus & payment records</li><li><Check size={15}/>Role-based access & printable statements</li></ul><button className={'saas-button '+(i===1?'primary':'')} onClick={()=>onChoose(plan)}>{selectedId===plan.id?'Selected plan':preview?'Preview registration':'Choose '+plan.name}<ArrowRight size={16}/></button></article>)}</div>;}
export function Submit({busy,children,...props}){return <button className="saas-button primary" disabled={busy||props.disabled} {...props}>{busy?<LoaderCircle size={17} className="spin"/>:null}{busy?'Please wait…':children}</button>;}
