import React,{useEffect,useState} from 'react';
import {Mail,MessageCircle,RefreshCw,Wallet,Plus,ShieldCheck} from 'lucide-react';
import {saasApi,currency,date,loadCheckout} from './api.js';
import {channels} from '../../shared/integrations.js';
import {Notice,Loading} from './components.jsx';
import './messaging.css';
const emptyPrefs={channels:{email:false,sms:false,whatsapp:false},owner_alerts:false,customer_alerts:false};
const emptyData={summary:{balances:{},counts:{},charged:{}},jobs:[],events:[],packs:[],grants:[],orders:[],organizations:[],plans:[],allowances:[],preferences:emptyPrefs,consents:[],clients:[]};
export default function Messages({platform=false,preview=false}){
 const [data,setData]=useState(null),[tenant,setTenant]=useState(''),[tab,setTab]=useState('Activity'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[prefs,setPrefs]=useState(emptyPrefs),[pack,setPack]=useState({name:'',channel:'email',credits:100,price_paise:10000,active:false}),[grant,setGrant]=useState({tenant_id:'',channel:'email',credits:100,reason:'',expires_at:'',request_id:crypto.randomUUID()}),[allowance,setAllowance]=useState({scope:'plan',scope_id:'',channel:'email',credits:100,rollover:false}),[reconcile,setReconcile]=useState(null),[evidence,setEvidence]=useState(''),[accepted,setAccepted]=useState(false),[orderFix,setOrderFix]=useState(null),[orderId,setOrderId]=useState(''),[consent,setConsent]=useState({client_id:'',channel:'email',allowed:false,evidence:''});
 const base=platform?'/platform/messages':'/messages';
 async function load(){try{setError('');const d=preview?emptyData:await saasApi(base+(platform&&tenant?'?tenant='+tenant:''));setData(d);setPrefs(d.preferences||emptyPrefs);}catch(e){setError(e.message);}}
 useEffect(()=>{setData(null);load();},[tenant,platform,preview]);
 async function action(path,body,success='Changes saved.'){setBusy(true);setError('');setNotice('');try{await saasApi(base+path,'POST',body);setNotice(success);await load();return true;}catch(e){setError(e.message);return false;}finally{setBusy(false);}}
 async function buy(p){setBusy(true);setError('');try{await loadCheckout();const o=await saasApi('/messages/recharge','POST',{packId:p.id});new window.Razorpay({...o,handler:async response=>{await action('/recharge/verify',{id:o.id,paymentId:response.razorpay_payment_id},'Payment verified. Credits added.');},modal:{ondismiss:()=>{setNotice('Checkout closed. Refresh the recharge below if payment was made; do not pay twice.');load();}}}).open();await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const disabled=preview||busy;
 const channelSelect=(value,onChange)=><select value={value} onChange={e=>onChange(e.target.value)}>{channels.map(c=><option key={c} value={c}>{c==='whatsapp'?'WhatsApp':c==='sms'?'SMS':'Email'}</option>)}</select>;
 const submit=(fn)=>(e)=>{e.preventDefault();fn();};
 const set=(setter,key,value)=>setter(v=>({...v,[key]:value}));
 return <div className="messaging-page"><div className="saas-page-heading"><div><span className="saas-eyebrow">COMMUNICATION CENTER</span><h1>{platform?'Every message. Every credit.':'Messages & credits'}</h1><p>{platform?'Manage channel balances, recharge packs and included allowances.':'Send booking confirmations responsibly, with full control of your balance.'}</p></div><button className="saas-button" onClick={load} disabled={busy}><RefreshCw size={16}/>Refresh</button></div>
 {preview&&<Notice>Design preview. No real messages, credits or purchases. Actions are disabled.</Notice>}{error&&<Notice error>{error}</Notice>}{notice&&<Notice>{notice}</Notice>}
 {data?<>{!data.workerEnabled&&<Notice>Automatic dispatch is disabled on the server. Settings and balances can be prepared before enabling the worker.</Notice>}
 {platform&&<label className="message-org-filter">Report scope<select value={tenant} onChange={e=>setTenant(e.target.value)}><option value="">All organizations</option>{data.organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>}
 <div className="message-wallets">{channels.map(c=>{const n=data.summary.counts[c]||{};return <section className="saas-panel message-wallet" key={c}><div><span>{c==='whatsapp'?'WhatsApp':c==='sms'?'SMS':'Email'}</span>{c==='email'?<Mail size={20}/>:<MessageCircle size={20}/>}</div><strong>{Number(data.summary.balances[c]||0).toLocaleString('en-IN')} <small>available credits</small></strong><dl><div><dt>Sent / accepted</dt><dd>{n.sent||0}</dd></div><div><dt>Held</dt><dd>{n.held||0}</dd></div><div><dt>Failed</dt><dd>{n.failed||0}</dd></div><div><dt>Queued / processing</dt><dd>{(n.queued||0)+(n.processing||0)}</dd></div><div><dt>Uncertain</dt><dd>{n.unknown||0}</dd></div><div><dt>Credits charged</dt><dd>{data.summary.charged[c]||0}</dd></div></dl></section>;})}</div>
 <p className="message-explainer">One credit per recipient and accepted provider message. “Sent” means provider accepted, not confirmed delivery. Uncertain sends keep their reservation; failed sends release it. Provider bills, SMS segment costs and delivery receipts are not shown as wallet credits.</p>
 <div className="message-tabs" role="tablist" aria-label="Communication sections">{['Activity',platform?'Credits & plans':'Buy credits',...(platform?[]:['Notifications & consent']),'Credit ledger'].map(t=><button role="tab" aria-selected={tab===t} className={tab===t?'selected':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div>
 {tab==='Activity'&&<section className="saas-panel integration-card"><h2>Message activity</h2><p>Latest 100 attempts · summary totals above cover all history. Automatic confirmations are queued once per booking, recipient and channel.</p><div className="saas-table-wrap"><table className="saas-table"><thead><tr>{platform&&<th>Organization</th>}<th>Booking / recipient</th><th>Channel</th><th>Status</th><th>Details</th><th>Created</th><th>Action</th></tr></thead><tbody>{data.jobs.map(j=><tr key={j.id}>{platform&&<td>{data.organizations.find(o=>o.id===j.tenant_id)?.name||j.tenant_id}</td>}<td><code>{j.booking_id}</code><small>{j.recipient}</small></td><td>{j.channel}</td><td><span className={'message-state '+j.status}>{j.status}</span></td><td>{j.reason}{j.provider_id&&<small>Provider: {j.provider_id}</small>}</td><td>{date(j.created_at)}</td><td>{j.status==='held'&&<button className="saas-button" disabled={disabled} onClick={()=>action('/retry',{id:j.id},'Queued for fresh consent, balance and configuration checks.')}>Retry checks</button>}{j.status==='unknown'&&(platform?<button className="saas-button" disabled={disabled} onClick={()=>{setReconcile(j.id);setEvidence('');setAccepted(false);}}>Reconcile</button>:<small>Contact platform support for provider reconciliation. Do not resend.</small>)}</td></tr>)}</tbody></table>{!data.jobs.length&&<div className="saas-empty">No message attempts yet. Enable notifications before confirming a new booking.</div>}</div></section>}
 {tab==='Credits & plans'&&platform&&<><div className="integration-grid"><form className="saas-panel integration-card" onSubmit={submit(async()=>{if(await action('/grant',{...grant,expires_at:grant.expires_at?new Date(grant.expires_at).toISOString():null},'Credits allocated.'))setGrant(g=>({...g,request_id:crypto.randomUUID()}));})}><h2><Plus size={20}/>Allocate credits</h2><p>One-time promotional, referral or support credit. A reason is recorded in the audit trail.</p><fieldset disabled={disabled}><label>Organization<select required value={grant.tenant_id} onChange={e=>set(setGrant,'tenant_id',e.target.value)}><option value="">Choose organization</option>{data.organizations.map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select></label><label>Channel{channelSelect(grant.channel,v=>set(setGrant,'channel',v))}</label><label>Credits<input type="number" min="1" max="1000000" required value={grant.credits} onChange={e=>set(setGrant,'credits',Number(e.target.value))}/></label><label>Expiry (blank = no expiry)<input type="datetime-local" value={grant.expires_at} onChange={e=>set(setGrant,'expires_at',e.target.value)}/></label><label>Reason<textarea required minLength={5} maxLength={300} value={grant.reason} onChange={e=>set(setGrant,'reason',e.target.value)} placeholder="Referral promotion / support credit…"/></label><button className="saas-button primary">Allocate credits</button></fieldset></form>
 <form className="saas-panel integration-card" onSubmit={submit(()=>action('/allowance',allowance,'Allowance saved for future paid billing periods. No retroactive credits added.'))}><h2>Included plan credits</h2><p>Organization rules override plan rules per channel. Zero disables that channel’s allowance. Settings affect future verified paid renewals, not the current balance.</p><fieldset disabled={disabled}><label>Apply to<select value={allowance.scope} onChange={e=>setAllowance(a=>({...a,scope:e.target.value,scope_id:''}))}><option value="plan">Specific subscription plan</option><option value="organization">Specific organization</option></select></label><label>{allowance.scope==='plan'?'Plan':'Organization'}<select required value={allowance.scope_id} onChange={e=>set(setAllowance,'scope_id',e.target.value)}><option value="">Choose…</option>{(allowance.scope==='plan'?data.plans:data.organizations).map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Channel{channelSelect(allowance.channel,v=>set(setAllowance,'channel',v))}</label><label>Credits per paid billing period<input type="number" min="0" max="1000000" required value={allowance.credits} onChange={e=>set(setAllowance,'credits',Number(e.target.value))}/></label><label>Unused included credits<select value={allowance.rollover?'rollover':'expire'} onChange={e=>set(setAllowance,'rollover',e.target.value==='rollover')}><option value="expire">Expire at end of paid period</option><option value="rollover">Carry forward without expiry</option></select></label><button className="saas-button primary">Save allowance</button></fieldset></form>
 <form className="saas-panel integration-card" onSubmit={submit(()=>action('/pack',pack,'Recharge pack saved.'))}><h2>{pack.id?'Edit':'Create'} recharge pack</h2><p>INR purchases are credited only after server-verified Razorpay capture. Prices below are the final charge; confirm your tax obligations before publishing.</p><fieldset disabled={disabled}><label>Name<input required maxLength={80} value={pack.name} onChange={e=>set(setPack,'name',e.target.value)}/></label><label>Channel{channelSelect(pack.channel,v=>set(setPack,'channel',v))}</label><label>Credits<input required type="number" min="1" max="1000000" value={pack.credits} onChange={e=>set(setPack,'credits',Number(e.target.value))}/></label><label>Final price (₹)<input required type="number" min="1" max="1000000" step="0.01" value={pack.price_paise/100} onChange={e=>set(setPack,'price_paise',Math.round(Number(e.target.value)*100))}/></label><label className="message-toggle"><input type="checkbox" checked={pack.active} onChange={e=>set(setPack,'active',e.target.checked)}/>Available for purchase</label><button className="saas-button primary">Save pack</button>{pack.id&&<button type="button" className="saas-button" onClick={()=>setPack({name:'',channel:'email',credits:100,price_paise:10000,active:false})}>New pack</button>}</fieldset></form></div>
 <section className="saas-panel integration-card"><h2>Allowance rules</h2><div className="saas-table-wrap"><table className="saas-table"><thead><tr><th>Applies to</th><th>Channel</th><th>Credits / paid period</th><th>Unused credits</th><th>Edit</th></tr></thead><tbody>{data.allowances.map(a=><tr key={a.scope+a.scope_id+a.channel}><td>{a.scope} · {(a.scope==='plan'?data.plans:data.organizations).find(o=>o.id===a.scope_id)?.name||a.scope_id}</td><td>{a.channel}</td><td>{a.credits}</td><td>{a.rollover?'Carry forward':'Expire'}</td><td><button className="saas-button" onClick={()=>setAllowance(a)}>Edit rule</button></td></tr>)}</tbody></table></div></section></>}
 {(tab==='Buy credits'||tab==='Credits & plans')&&<><section className="saas-panel integration-card"><h2><Wallet size={21}/>Recharge packs</h2><p>Purchased credits do not expire. Credit balances are not cash or a transferable wallet.</p><div className="message-packs">{data.packs.map(p=><article key={p.id}><span>{p.channel} · {p.active?'Available':'Unpublished'}</span><h3>{p.name}</h3><strong>{p.credits.toLocaleString()} credits</strong><p>{currency(p.price_paise)}</p>{platform?<button className="saas-button" onClick={()=>setPack(p)}>Edit pack</button>:<button disabled={disabled} className="saas-button primary" onClick={()=>buy(p)}>Buy credits</button>}</article>)}</div>{!data.packs.length&&<p>No recharge packs available yet.</p>}</section>
 <section className="saas-panel integration-card"><h2>Recent recharges</h2><p>Latest 30 orders. If checkout was interrupted, refresh the payment rather than buying again.</p><div className="saas-table-wrap"><table className="saas-table"><thead><tr><th>Pack</th><th>Amount</th><th>Status</th><th>Created</th><th>Payment check</th></tr></thead><tbody>{data.orders.map(o=><tr key={o.id}><td>{o.pack.name}</td><td>{currency(o.pack.price_paise)}</td><td>{o.status}</td><td>{date(o.created_at)}</td><td>{!platform&&o.status==='pending'&&<button className="saas-button" disabled={disabled} onClick={()=>action('/recharge/refresh',{id:o.id},'Payment verified and credited.')}>Refresh payment</button>}{o.status==='creating'&&(platform?<button className="saas-button" onClick={()=>{setOrderFix(o.id);setOrderId('');}}>Reconcile order</button>:'Contact support before retrying checkout.')}</td></tr>)}</tbody></table></div></section></>}
 {tab==='Notifications & consent'&&!platform&&<><div className="integration-grid"><form className="saas-panel integration-card" onSubmit={submit(()=>action('/preferences',prefs,'Notification preferences saved. Applies to new confirmation events.'))}><h2>Automatic booking confirmations</h2><p>Off by default. Each recipient uses one credit per enabled channel. Owner alerts use your organization’s billing email and phone.</p><fieldset disabled={disabled}>{channels.map(c=><label key={c} className="message-toggle"><input type="checkbox" checked={!!prefs.channels[c]} onChange={e=>setPrefs(p=>({...p,channels:{...p.channels,[c]:e.target.checked}}))}/>{c==='sms'?'SMS':c==='whatsapp'?'WhatsApp':'Email'}</label>)}<label className="message-toggle"><input type="checkbox" checked={prefs.owner_alerts} onChange={e=>set(setPrefs,'owner_alerts',e.target.checked)}/>Send to me (I consent to owner alerts)</label><label className="message-toggle"><input type="checkbox" checked={prefs.customer_alerts} onChange={e=>set(setPrefs,'customer_alerts',e.target.checked)}/>Send to customers with recorded channel consent</label><button className="saas-button primary">Save notification preferences</button></fieldset></form>
 <form className="saas-panel integration-card" onSubmit={submit(()=>action('/consent',consent,'Consent record saved for the current customer contact.'))}><h2><ShieldCheck size={20}/>Customer consent</h2><p>Record genuine permission and its source. Do not assume an existing booking is permission to send SMS or WhatsApp. Changing a contact requires fresh consent.</p><fieldset disabled={disabled}><label>Customer<select required value={consent.client_id} onChange={e=>set(setConsent,'client_id',e.target.value)}><option value="">Choose customer</option>{data.clients.map(c=><option key={c.id} value={c.id}>{c.body.name} · {c.body.email||c.body.phone}</option>)}</select></label><label>Channel{channelSelect(consent.channel,v=>set(setConsent,'channel',v))}</label><label>Permission<select value={consent.allowed?'yes':'no'} onChange={e=>set(setConsent,'allowed',e.target.value==='yes')}><option value="no">Withdrawn / not allowed</option><option value="yes">Permission received</option></select></label><label>Evidence / withdrawal source<textarea required minLength={5} maxLength={500} value={consent.evidence} onChange={e=>set(setConsent,'evidence',e.target.value)} placeholder="Signed booking consent on date / customer requested opt-out…"/></label><button className="saas-button primary">Record consent</button></fieldset></form></div>
 <section className="saas-panel integration-card"><h2>Consent register</h2><p>Latest 1,000 records. Use the form above to revoke permission immediately for future dispatch checks.</p><div className="saas-table-wrap"><table className="saas-table"><thead><tr><th>Customer</th><th>Channel</th><th>Permission</th><th>Contact</th><th>Updated</th></tr></thead><tbody>{data.consents.map(c=><tr key={c.client_id+c.channel}><td>{data.clients.find(x=>x.id===c.client_id)?.body.name||c.client_id}</td><td>{c.channel}</td><td>{c.allowed?'Allowed':'Withdrawn'}</td><td>{c.destination}</td><td>{date(c.updated_at)}</td></tr>)}</tbody></table></div></section></>}
 {platform&&reconcile&&<form className="saas-panel integration-card" onSubmit={submit(async()=>{if(await action('/reconcile',{id:reconcile,accepted,evidence},'Provider outcome reconciled.'))setReconcile(null);})}><h2>Reconcile uncertain send</h2><p>Check the provider’s logs first. Never mark rejected unless you have evidence that the provider did not accept this send. No automatic resend follows this action.</p><fieldset disabled={disabled}><label>Verified provider result<select value={accepted?'accepted':'rejected'} onChange={e=>setAccepted(e.target.value==='accepted')}><option value="rejected">Definitely rejected / not accepted — release reservation</option><option value="accepted">Accepted — charge reserved credit</option></select></label><label>Provider reference and evidence<textarea required minLength={10} maxLength={500} value={evidence} onChange={e=>setEvidence(e.target.value)}/></label><button className="saas-button primary">Confirm reconciliation</button><button type="button" className="saas-button" onClick={()=>setReconcile(null)}>Cancel</button></fieldset></form>}
 {platform&&orderFix&&<form className="saas-panel integration-card" onSubmit={submit(async()=>{if(await action('/reconcile-order',{id:orderFix,orderId},'Order verified and linked.'))setOrderFix(null);})}><h2>Reconcile recharge order</h2><p>Find the Razorpay order whose receipt is <code>{orderFix}</code>. The server checks the order identity and amount. Do not create another payment.</p><fieldset disabled={disabled}><label>Razorpay order ID<input required pattern="order_[A-Za-z0-9]+" value={orderId} onChange={e=>setOrderId(e.target.value)}/></label><button className="saas-button primary">Verify provider order</button><button className="saas-button" type="button" onClick={()=>setOrderFix(null)}>Cancel</button></fieldset></form>}
 {tab==='Credit ledger'&&<><section className="saas-panel integration-card"><h2>Credit allocations</h2><p>Latest 100 grants. Available balances exclude expired grants and all reserved credits.</p><div className="saas-table-wrap"><table className="saas-table"><thead><tr><th>Channel</th><th>Granted</th><th>Used / reserved</th><th>Expires</th><th>Reason</th></tr></thead><tbody>{data.grants.map(g=><tr key={g.id}><td>{g.channel}</td><td>{g.credits}</td><td>{g.used}</td><td>{g.expires_at?date(g.expires_at):'Never'}</td><td>{g.reason}</td></tr>)}</tbody></table></div></section><section className="saas-panel integration-card"><h2>Ledger events</h2><p>Latest 100 events. Reserve then charge describes one credit, not two deductions.</p><div className="saas-table-wrap"><table className="saas-table"><thead><tr><th>When</th><th>Channel</th><th>Action</th><th>Credits</th><th>Reference</th></tr></thead><tbody>{data.events.map(e=><tr key={e.id}><td>{date(e.created_at)}</td><td>{e.channel}</td><td>{e.action}</td><td>{e.credits}</td><td><code>{e.reference}</code></td></tr>)}</tbody></table></div></section></>}
 </>:!error&&<Loading/>}
 </div>;
}
