import React,{useMemo,useState} from 'react';
import {Building2,CreditCard,Layers3,ShieldCheck,ArrowUpRight,Plus,Globe,Mail,CheckCircle2,AlertTriangle} from 'lucide-react';
import {Badge} from './components.jsx';
import {currency,date} from './api.js';
import {platformSeries} from '../../shared/platform-series.js';
export default function PlatformOverview({data,tenants,navigate,onCreatePlan}){
 const [months,setMonths]=useState(6);
 const rows=useMemo(()=>platformSeries(data,months),[data,months]);
 const total=rows.reduce((sum,r)=>sum+r.revenue,0),orgTotal=rows.reduce((sum,r)=>sum+r.organizations,0);
 const readiness=[['Tenant database',data.setup.database,'Supabase connection',Building2],['Administrator verification',data.setup.mfa,'MFA required',ShieldCheck],['Live payments',data.setup.billing&&data.setup.billingMode==='live',data.setup.billingMode==='test'?'Test mode / not live':'Razorpay configuration',CreditCard],['HTTPS',data.setup.https,'Public application URL',ShieldCheck]];
 const totalMix=data.subscriptions.length;
 const mix=data.plans.map(p=>({...p,count:data.subscriptions.filter(s=>s.plan_id===p.id).length}));
 const unmatched=totalMix-mix.reduce((sum,p)=>sum+p.count,0);if(unmatched>0)mix.push({id:'other',name:'Other plans',count:unmatched});
 const colors=['#665ac5','#9b8def','#c9c2f7','#adaec4'];let position=0;
 const stops=mix.filter(p=>p.count).map((p,i)=>{const start=position;position+=p.count/Math.max(1,totalMix)*100;return `${colors[i%colors.length]} ${start}% ${position}%`;});
 return <div className="platform-overview">
 <div className="platform-kpis">{[['Organizations',data.metrics.organizations,'Registered businesses',Building2],['Gross collections',currency(data.metrics.grossCollectedPaise),'SaaS payments · before refunds',CreditCard],['Active subscriptions',data.metrics.activeSubscriptions,`${data.metrics.trials} on trial`,Layers3],['Estimated MRR',currency(data.metrics.mrrPaise),'Annual plans normalized',CreditCard]].map(([label,value,hint,Icon])=><article className="saas-panel" key={label}><span className="platform-kpi-icon"><Icon size={23}/></span><div><span>{label}</span><strong>{value}</strong><small>{hint}</small></div></article>)}</div>
 <div className="platform-range"><span>Platform activity · {rows[0].full} – {rows.at(-1).full} <small>UTC · current month is partial</small></span><label><span className="sr-only">Chart period</span><select value={months} onChange={e=>setMonths(Number(e.target.value))}><option value={6}>Last 6 months</option><option value={3}>Last 3 months</option><option value={12}>Last 12 months</option></select></label></div>
 <div className="platform-charts"><section className="saas-panel"><div className="saas-panel-heading"><h2><Building2 size={18}/>Organization growth</h2><strong>{orgTotal} new</strong></div><Chart rows={rows} field="organizations" label="New organizations"/><p className="platform-chart-note">Registrations per month</p></section><section className="saas-panel"><div className="saas-panel-heading"><h2><CreditCard size={18}/>Subscription collections</h2><strong>{currency(total)}</strong></div><Chart rows={rows} field="revenue" line label="Captured SaaS payments"/><p className="platform-chart-note">Not venue booking revenue or net settlements</p></section><section className="saas-panel"><div className="saas-panel-heading"><h2><ShieldCheck size={18}/>Platform readiness</h2></div><div className="platform-ready">{readiness.map(([label,ok,hint,Icon])=><div key={label}><Icon size={18}/><div><strong>{label}</strong><small>{hint}</small></div><Badge value={ok?'ready':'setup'}/></div>)}</div><button className="saas-panel-link" onClick={()=>navigate('Launch checklist')}>Review setup <ArrowUpRight size={14}/></button></section></div>
 <div className="platform-secondary">{[['Marriage halls',(data.usage||[]).reduce((n,r)=>n+Number(r.halls||0),0)],['Active staff',(data.usage||[]).reduce((n,r)=>n+Number(r.staff||0),0)],['Published plans',data.plans.filter(p=>p.published).length],['Suspended organizations',data.metrics.suspended||0]].map(([label,n])=><article className="saas-panel" key={label}><span>{label}</span><strong>{n}</strong></article>)}</div>
 <section className="saas-panel"><div className="saas-panel-heading"><h2>Recent organizations</h2><button className="saas-text-button" onClick={()=>navigate('Organizations')}>View all <ArrowUpRight size={14}/></button></div>{tenants(data.organizations.slice(0,5))}</section>
 <div className="platform-bottom"><section className="saas-panel"><div className="saas-panel-heading"><h2>Subscription mix</h2></div><div className="platform-mix"><div className="platform-donut" style={{background:stops.length?`conic-gradient(${stops.join(',')})`:'var(--border)'}}><div><strong>{totalMix}</strong><small>Subscriptions</small></div></div><ul>{mix.map((p,i)=><li key={p.id}><i style={{background:colors[i%colors.length]}}/><span>{p.name}</span><strong>{p.count}</strong></li>)}</ul></div>{!totalMix&&<p className="platform-chart-note">No subscriptions yet.</p>}</section><section className="saas-panel"><div className="saas-panel-heading"><h2>Quick actions</h2></div><div className="platform-actions">{[['Organizations',Building2,()=>navigate('Organizations')],['Create plan',Plus,onCreatePlan],['Website CMS',Globe,()=>navigate('Website CMS')],['Messages',Mail,()=>navigate('Messages & credits')]].map(([name,Icon,click])=><button key={name} onClick={click}><Icon size={23}/><span>{name}</span></button>)}</div></section><section className="saas-panel"><div className="saas-panel-heading"><h2>Latest activity</h2><button className="saas-text-button" onClick={()=>navigate('Audit trail')}>View all <ArrowUpRight size={14}/></button></div><div className="platform-activity">{data.audit.slice(0,4).map(a=><div key={a.id}><CheckCircle2 size={15}/><span>{a.action.replaceAll('.',' · ')}</span><time>{date(a.created_at)}</time></div>)}{!data.audit.length&&<p>No activity recorded yet.</p>}{!data.setup.billing&&<div><AlertTriangle size={15}/><span>Payment gateway setup pending</span></div>}</div></section></div>
 </div>;
}
function Chart({rows,field,line=false,label}){
 const max=Math.max(1,...rows.map(r=>r[field])),width=440,height=175,step=width/rows.length;
 const y=value=>height-value/max*(height-20),points=rows.map((r,i)=>`${i*step+step/2},${y(r[field])}`).join(' ');
 return <div className="platform-chart"><svg viewBox="-5 -8 450 218" role="img" aria-label={`${label}: ${rows.map(r=>`${r.full}: ${field==='revenue'?currency(r[field]):r[field]}`).join('; ')}`}>
 {[0,.25,.5,.75,1].map(f=><line key={f} x1="0" x2={width} y1={y(max*f)} y2={y(max*f)} stroke="var(--border)" strokeDasharray={f?'3 4':undefined}/>)}
 {line&&<><polygon points={`${step/2},${height} ${points} ${width-step/2},${height}`} fill="var(--primary)" opacity=".08"/><polyline points={points} fill="none" stroke="var(--primary)" strokeWidth="2.5"/></>}
 {rows.map((r,i)=><g key={r.key}><title>{r.full}: {field==='revenue'?currency(r[field]):r[field]}</title>{line?<circle cx={i*step+step/2} cy={y(r[field])} r="4" fill="var(--primary)" stroke="var(--surface)" strokeWidth="2"/>:<rect x={i*step+step*.24} y={y(r[field])} width={step*.52} height={height-y(r[field])} rx="3" fill="var(--primary)" opacity=".8"/>}<text x={i*step+step/2} y="196" textAnchor="middle" fill="var(--text-muted)" fontSize="10">{r.label}</text>{!line&&<text x={i*step+step/2} y={y(r[field])-5} textAnchor="middle" fill="var(--text-secondary)" fontSize="10">{r[field]}</text>}</g>)}
 </svg><details><summary>View chart data</summary><table><thead><tr><th>Month</th><th>{label}</th></tr></thead><tbody>{rows.map(r=><tr key={r.key}><td>{r.full}</td><td>{field==='revenue'?currency(r[field]):r[field]}</td></tr>)}</tbody></table></details></div>;
}
