import React,{useEffect,useRef,useState} from 'react';
import {LockKeyhole,ShieldCheck,Save,Mail,MessageCircle,CreditCard,Check,Copy,ArrowUpRight,RotateCcw,Bell,Palette} from 'lucide-react';
import {saasApi} from './api.js';
import {Notice,Loading} from './components.jsx';
import {integrationFields,providerPlaceholders,providerInputError} from '../../shared/integrations.js';
import './messaging.css';
const names={razorpay:'Payments',email:'Email',sms:'SMS',whatsapp:'WhatsApp',fcm:'Push (FCM)'};
const icons={razorpay:CreditCard,email:Mail,sms:MessageCircle,whatsapp:MessageCircle,fcm:Bell};
const initial=()=>({settings:Object.fromEntries(Object.keys(integrationFields).map(k=>[k,{enabled:false,revision:0,fields:{},secrets:{}}])),encryptionReady:false,workerEnabled:false,runtimeBilling:{enabled:false,mode:'off'},razorpaySource:'Design preview'});
const defaultBrandingValues={logoText:'Gatherhall',logoUrl:'',title:'Gatherhall',tagline:'Every celebration, beautifully managed',description:'',supportEmail:'',footerNote:''};
function BrandingCard({preview}){
 const [data,setData]=useState(null),[values,setValues]=useState(defaultBrandingValues),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const request=useRef(0);
 async function load(){const n=++request.current;try{const d=preview?{values:defaultBrandingValues,revision:0,updatedAt:null}:await saasApi('/platform/branding');if(n!==request.current)return;setData(d);setValues({...defaultBrandingValues,...d.values});setError('');}catch(e){if(n===request.current)setError(e.message);}}
 useEffect(()=>{load();},[preview]);
 const dirty=data&&JSON.stringify(values)!==JSON.stringify({...defaultBrandingValues,...data.values});
 async function save(e){e.preventDefault();if(preview||busy)return;setBusy(true);setError('');setNotice('');try{await saasApi('/platform/branding','POST',{values,revision:data?data.revision:0});setNotice('Branding saved. Login page and workspaces pick it up within a few seconds.');await load();}catch(err){setError(err.message);}finally{setBusy(false);}}
 const set=(k,v)=>setValues(s=>({...s,[k]:v}));
 return <section className="saas-panel integration-card branding-card"><div className="integration-title"><span><Palette size={23}/></span><div><h2>SaaS branding</h2><small>{data?.updatedAt?'Last saved '+new Date(data.updatedAt).toLocaleString():'Using the default Gatherhall identity'}</small></div><span className="message-state">{dirty?'Unsaved':'Saved'}</span></div>
 <p>Name, logo, description and support contact shown on the sign-in page, marketing footer and support flows. Leave fields blank to use defaults.</p>
 {error&&<Notice error>{error}</Notice>}{notice&&<Notice>{notice}</Notice>}
 <form onSubmit={save} autoComplete="off"><fieldset disabled={preview||busy}><div className="integration-fields branding-fields">
  <label><span>Product title</span><input maxLength={60} value={values.title} onChange={e=>set('title',e.target.value)} placeholder="Gatherhall"/></label>
  <label><span>Logo text (monogram)</span><input maxLength={12} value={values.logoText} onChange={e=>set('logoText',e.target.value)} placeholder="Gatherhall"/></label>
  <label><span>Logo image URL (optional)</span><input type="url" maxLength={500} value={values.logoUrl} onChange={e=>set('logoUrl',e.target.value)} placeholder="https://your-domain.com/logo.png"/></label>
  <label><span>Tagline</span><input maxLength={120} value={values.tagline} onChange={e=>set('tagline',e.target.value)} placeholder="Every celebration, beautifully managed"/></label>
  <label><span>Support email (optional)</span><input type="email" maxLength={120} value={values.supportEmail} onChange={e=>set('supportEmail',e.target.value)} placeholder="support@your-domain.com"/></label>
  <label><span>Footer note (optional)</span><input maxLength={200} value={values.footerNote} onChange={e=>set('footerNote',e.target.value)} placeholder="© Your company · privacy · terms"/></label>
  <label className="full"><span>Description</span><textarea maxLength={400} rows={2} value={values.description} onChange={e=>set('description',e.target.value)} placeholder="What is this platform, in one sentence?"/></label>
 </div></fieldset>
 <div className="provider-savebar"><span>{dirty?'You have unsaved changes':'Sign-in page and support flows use these values'}</span><div><button type="button" className="saas-button" disabled={busy||!dirty} onClick={()=>setValues({...defaultBrandingValues,...(data?.values||{})})}><RotateCcw size={14}/>Discard</button><button className="saas-button primary" disabled={preview||busy||!dirty}><Save size={15}/>{busy?'Saving…':'Save branding'}</button></div></div></form></section>;
}
export default function PlatformSettings({preview=false}){
 const [data,setData]=useState(null),[drafts,setDrafts]=useState({}),[active,setActive]=useState('razorpay'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[showSetup,setShowSetup]=useState(false),[copied,setCopied]=useState('');
 const request=useRef(0),saving=useRef(false);
 async function load(only){const n=++request.current;try{const d=preview?initial():await saasApi('/platform/settings');if(n!==request.current)return;setData(d);setDrafts(prev=>only?{...prev,[only]:structuredClone(d.settings[only])}:structuredClone(d.settings));setError('');}catch(e){if(n===request.current)setError(e.message);}}
 useEffect(()=>{load();return()=>{request.current++;};},[preview]);
 const dirty=k=>!!data&&JSON.stringify(drafts[k])!==JSON.stringify(data.settings[k]);
 const anyDirty=data&&Object.keys(drafts).some(dirty);
 useEffect(()=>{if(!anyDirty)return;const warn=e=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[anyDirty]);
 const change=(key,value)=>setDrafts(d=>({...d,[active]:{...d[active],...(key==='enabled'?{enabled:value}:{fields:{...d[active].fields,[key]:value,...(['flowId','template','language'].includes(key)?{approved:'false'}:{})}})}}));
 async function save(e){e.preventDefault();if(saving.current||preview)return;saving.current=true;setBusy(true);setError('');setNotice('');const kind=active;try{const s=drafts[kind];for(const [key,value] of Object.entries(s.fields)){const problem=providerInputError(kind,key,value);if(problem)throw Error(problem);}await saasApi('/platform/settings/'+kind,'POST',{enabled:s.enabled,revision:s.revision,fields:s.fields});setNotice(kind==='razorpay'?'Saved. Restart all app instances to apply payment changes.':'Provider settings saved. This does not verify delivery.');await load(kind);}catch(e){setError(e.message);}finally{saving.current=false;setBusy(false);}}
 async function copy(text,label){try{await navigator.clipboard.writeText(text);setCopied(label);}catch{setError('Clipboard unavailable. Select and copy the value manually.');}}
 const code="node -e \"console.log(require('node:crypto').randomBytes(32).toString('base64'))\"";
 if(!data)return <div className="messaging-page">{error?<Notice error>{error} <button onClick={()=>load()}>Retry loading settings</button></Notice>:<Loading/>}</div>;
 const s=drafts[active],definition=integrationFields[active],Icon=icons[active],saved=data.settings[active];
 const invalid=definition.fields.some(([key])=>providerInputError(active,key,s.fields[key]||''));
 const locked=preview||busy||!data.encryptionReady;
 return <div className="messaging-page settings-v2">

 {preview&&<Notice>Design preview. Real credentials and saving are disabled.</Notice>}{error&&<Notice error>{error} <button type="button" className="saas-button" disabled={busy} onClick={()=>{if(!dirty(active)||window.confirm('Discard changes to this provider and reload its saved settings?'))load(active);}}>Reload saved provider</button></Notice>}{notice&&<Notice>{notice}</Notice>}
 <section className={'settings-readiness '+(!data.encryptionReady?'needs-setup':'')}><div><LockKeyhole size={22}/><div><strong>{data.encryptionReady?'Credential encryption is ready':'One setup step before saving providers'}</strong><p>{data.encryptionReady?'Secrets stay on your server. Saved passwords are never returned to the browser.':'Add a valid encryption key in Coolify. Provider fields are locked until it is ready.'}</p></div></div><button className="saas-button" aria-expanded={showSetup} onClick={()=>setShowSetup(v=>!v)}>{showSetup?'Hide instructions':'Setup instructions'}</button></section>
 {showSetup&&<section className="saas-panel integration-card setup-instructions"><h2>Set up encryption once</h2><ol><li>In your own terminal, generate a key:<div className="copy-code"><code>{code}</code><button type="button" className="saas-button" onClick={()=>copy(code,'command')}><Copy size={14}/>{copied==='command'?'Copied':'Copy command'}</button></div></li><li>Add the result as <code>INTEGRATION_ENCRYPTION_KEY</code> in Coolify. Enable runtime; disable buildtime. Keep a private backup and use the same key on every instance.</li><li>Redeploy, then reload this page. Never paste the generated key in chat or source code.</li></ol><p>Already saved encrypted credentials? Do not replace their key. Restore the original key or arrange a controlled re-encryption.</p><button className="saas-button" disabled={busy} onClick={()=>{if(!anyDirty||window.confirm('Reload and discard unsaved provider changes?'))load();}}>Recheck setup</button></section>}
 <div className="provider-selector" aria-label="Choose a provider">{Object.keys(integrationFields).map(kind=>{const PIcon=icons[kind],row=data.settings[kind];return <button key={kind} className={active===kind?'selected':''} aria-pressed={active===kind} onClick={()=>setActive(kind)} disabled={busy}><PIcon size={21}/><span><strong>{names[kind]}</strong><small>{dirty(kind)?'Unsaved changes':row.revision?(row.enabled?'Saved · enabled':'Saved · disabled'):kind==='razorpay'&&data.runtimeBilling?.enabled?'Using server credentials':'Not configured'}</small></span>{dirty(kind)?<i className="unsaved-dot"/>:row.enabled?<Check size={16}/>:null}</button>;})}</div>
 <div className="provider-workspace"><form className="saas-panel integration-card provider-editor" autoComplete="off" onSubmit={save} key={active}>
 <div className="integration-title"><span><Icon size={23}/></span><div><h2>{definition.label}</h2><small>{saved.updatedAt?'Last saved '+new Date(saved.updatedAt).toLocaleString():'No dashboard configuration saved'}</small></div><span className={'message-state '+(dirty(active)?'held':saved.enabled?'sent':'')}>{dirty(active)?'Unsaved':saved.revision?(saved.enabled?'Saved · enabled':'Saved · disabled'):'Not configured'}</span></div>
 <p>{definition.hint}</p>
 <fieldset disabled={locked}><label className="message-toggle provider-enable"><input type="checkbox" checked={s.enabled} onChange={e=>change('enabled',e.target.checked)}/><span><strong>Enable this provider</strong><small>Changes apply only after saving{active==='razorpay'?' and restarting the app':''}.</small></span></label>
 <div className="integration-fields">{definition.fields.map(([key,label,secret,type])=>{const problem=providerInputError(active,key,s.fields[key]||''),id=`integration-${active}-${key}`;return <label key={key} htmlFor={id} className={type==='checkbox'?'message-toggle approval-field':''}>{type==='checkbox'?<><input id={id} type="checkbox" checked={s.fields[key]==='true'} onChange={e=>change(key,String(e.target.checked))}/>{label}</>:<><span>{label}{secret&&<LockKeyhole size={12}/>}</span>{key==='port'?<select id={id} aria-label={label} value={s.fields[key]||''} required={s.enabled} onChange={e=>change(key,e.target.value)}><option value="">Choose secure port</option><option value="587">587 · STARTTLS</option><option value="465">465 · TLS</option></select>:<input id={id} aria-label={label} name={`provider-${active}-${key}`} type={secret?'password':key==='from'?'email':'text'} autoComplete={secret?'new-password':'off'} data-lpignore="true" data-1p-ignore="true" spellCheck={false} autoCapitalize="none" required={s.enabled&&(!secret||!s.secrets[key])} aria-invalid={!!problem} aria-describedby={problem?`${id}-error`:undefined} maxLength={4096} placeholder={secret?(s.secrets[key]?'Saved securely — leave blank to keep':'Paste provider secret'):providerPlaceholders[key]||label} value={s.fields[key]||''} onChange={e=>change(key,e.target.value)}/ >}{problem&&<small className="field-error" id={`${id}-error`}>{problem}</small>}{secret&&s.secrets[key]&&<small>Leave blank to retain the saved secret.</small>}</>}</label>;})}</div></fieldset>
 <div className="provider-savebar"><span>{!data.encryptionReady?'Encryption setup required':dirty(active)?'You have unsaved changes':'No unsaved changes'}</span><div><button type="button" className="saas-button" disabled={busy||!dirty(active)} onClick={()=>setDrafts(d=>({...d,[active]:structuredClone(saved)}))}><RotateCcw size={14}/>Discard changes</button><button className="saas-button primary" disabled={locked||!dirty(active)||invalid}><Save size={15}/>{busy?'Saving…':'Save provider'}</button></div></div>
 </form><aside className="provider-help"><section className="saas-panel integration-card"><span className="saas-eyebrow">BEFORE YOU CONNECT</span><h2>{active==='razorpay'?'Payment readiness':'Sending readiness'}</h2>{active==='razorpay'?<><p>Running billing: <strong>{data.runtimeBilling?.enabled?data.runtimeBilling.mode+' mode':'Not configured'}</strong></p>{data.runtimeBilling?.restartRequired&&<Notice>Saved credentials differ from this running instance. Restart all instances to apply them.</Notice>}<p>Use API credentials from Razorpay—not your account email or login password. Keep the same provider account for existing mandates.</p></>:<><p>Message worker: <strong>{data.workerEnabled?'Enabled':'Disabled'}</strong></p><p>Saving credentials does not prove delivery. Enable the provider, record consent, allocate credits, then test a controlled booking confirmation.</p>{active==='email'&&<p>Signup and password-reset emails use Supabase SMTP, not this form.</p>}</>}<a className="saas-button" href="/platform#messages">Open messages & credits <ArrowUpRight size={14}/></a></section><section className="saas-panel integration-card"><h2>Protect your credentials</h2><p>Browsers and password managers may suggest your login details. Reject those suggestions—each service needs its own API credentials.</p><p>Never store secrets in frontend environment variables or share secret-bearing deployment logs.</p></section></aside></div>
 <BrandingCard preview={preview}/>
 {active==='razorpay'&&<section className="saas-panel integration-card"><h2>Webhook endpoints</h2><p>Configure these in Razorpay with the matching webhook secret.</p>{[['Subscriptions','/api/webhooks/razorpay'],['Credit recharges · payment.captured','/api/webhooks/credits']].map(([label,path])=><div className="webhook-row" key={path}><div><strong>{label}</strong><code>{location.origin+path}</code></div><button className="saas-button" onClick={()=>copy(location.origin+path,path)}><Copy size={14}/>{copied===path?'Copied':'Copy URL'}</button></div>)}</section>}
 </div>;
}
