import React,{useEffect,useState} from 'react';
import {LockKeyhole,ShieldCheck,Save,Mail,MessageCircle,CreditCard} from 'lucide-react';
import {saasApi} from './api.js';
import {Notice,Loading} from './components.jsx';
import {integrationFields} from '../../shared/integrations.js';
import './messaging.css';
export default function PlatformSettings({preview=false}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState('');
 const load=async()=>{try{setData(preview?{settings:Object.fromEntries(Object.keys(integrationFields).map(k=>[k,{enabled:false,revision:0,fields:{},secrets:{}}])),encryptionReady:false,workerEnabled:false,razorpaySource:'Design preview'}:await saasApi('/platform/settings'));}catch(e){setError(e.message);}};
 useEffect(()=>{load();},[]);
 const change=(kind,key,value)=>setData(d=>({...d,settings:{...d.settings,[kind]:{...d.settings[kind],...(key==='enabled'?{enabled:value}:{fields:{...d.settings[kind].fields,[key]:value,...(['flowId','template','language'].includes(key)?{approved:'false'}:{})}})}}}));
 async function save(e,kind){e.preventDefault();setBusy(kind);setError('');setNotice('');try{const r=await saasApi('/platform/settings/'+kind,'POST',data.settings[kind]);setNotice(r.restartRequired?'Saved. Restart all app instances in Coolify to apply Razorpay settings.':'Saved. Future message attempts use these settings.');await load();}catch(e){setError(e.message);}finally{setBusy('');}}
 return <div className="messaging-page"><div className="saas-page-heading"><div><span className="saas-eyebrow">PLATFORM SETTINGS</span><h1>Connected. Secure. In your control.</h1><p>Manage payments and communication providers for your venue network.</p></div><ShieldCheck size={30}/></div>
 {error&&<Notice error>{error} <button onClick={load}>Reload settings</button></Notice>}{notice&&<Notice>{notice}</Notice>}
 {!data?!error&&<Loading/>:<><div className="integration-security"><LockKeyhole size={24}/><div><strong>Server-only, encrypted credentials</strong><p>Saved secrets are never sent back to your browser. Leave password fields empty to keep an existing secret. Only MFA-verified platform administrators can change providers.</p></div></div>
 {preview&&<Notice>Design preview only. Do not enter real credentials. Saving is disabled.</Notice>}
 {!data.encryptionReady&&<Notice>Setup required: add INTEGRATION_ENCRYPTION_KEY in Coolify runtime variables before saving credentials. See docs/MESSAGING.md.</Notice>}
 <div className="integration-grid">{Object.entries(integrationFields).map(([kind,definition])=>{const s=data.settings[kind],Icon=kind==='razorpay'?CreditCard:kind==='email'?Mail:MessageCircle;return <form className="saas-panel integration-card" key={kind} onSubmit={e=>save(e,kind)}><div className="integration-title"><span><Icon size={23}/></span><h2>{definition.label}</h2><span className={'message-state '+(s.enabled?'sent':'held')}>{s.enabled?'Enabled':'Disabled'}</span></div><p>{definition.hint}</p><label className="message-toggle"><input type="checkbox" disabled={preview||!!busy} checked={s.enabled} onChange={e=>change(kind,'enabled',e.target.checked)}/>Enable this provider</label><div className="integration-fields">{definition.fields.map(([key,label,secret,type])=><label key={key} className={type==='checkbox'?'message-toggle':''}>{label}{secret&&s.secrets[key]&&<small>Saved securely · leave blank to retain</small>}{type==='checkbox'?<input disabled={preview||!!busy} type="checkbox" checked={s.fields[key]==='true'} onChange={e=>change(kind,key,String(e.target.checked))}/>:<input disabled={preview||!!busy} type={secret?'password':'text'} autoComplete="off" maxLength={4096} placeholder={secret&&s.secrets[key]?'••••••••':label} value={s.fields[key]||''} onChange={e=>change(kind,key,e.target.value)} />}</label>)}</div><button className="saas-button primary" disabled={preview||!!busy||!data.encryptionReady}><Save size={16}/>{busy===kind?'Saving…':'Save provider'}</button>{kind==='razorpay'&&<small>Source: {data.razorpaySource}. Other gateways are not enabled: each requires a billing adapter and verified webhook integration.</small>}</form>;})}</div>
 <section className="saas-panel integration-card"><h2>Delivery & deployment</h2><p>Message worker: <strong>{data.workerEnabled?'Enabled':'Disabled'}</strong>. Automatic messages also require each venue owner to enable channels, customer consent, available credits, and provider-approved templates.</p><p>Razorpay subscription webhook: <code>/api/webhooks/razorpay</code><br/>Credit recharge webhook (payment.captured): <code>/api/webhooks/credits</code></p><p>Authentication email is managed in Supabase → Authentication → SMTP. These email settings are for booking notifications only.</p></section></>}
 </div>;
}
