export const confirmationStyles = `
*{box-sizing:border-box}html{color-scheme:light}body{margin:0;background:#eef0f5;color:#182133;font-family:Arial,Helvetica,sans-serif;font-size:13px;line-height:1.6;-webkit-print-color-adjust:exact;print-color-adjust:exact}
a,button,input{touch-action:manipulation}button,a,input:focus-visible{outline-offset:3px}button:focus-visible,a:focus-visible,input:focus-visible{outline:3px solid #555e96}
.print-toolbar{position:sticky;top:0;z-index:2;background:#fff;border-bottom:1px solid #d8deea;padding:15px max(20px,calc((100% - 900px)/2));display:flex;align-items:center;justify-content:space-between;gap:20px;box-shadow:0 2px 12px #19203808}
.print-toolbar p{margin:0;font-size:12px;color:#526079}.toolbar-links{display:flex;align-items:center;gap:8px;flex-wrap:wrap;flex-shrink:0}button,.print-toolbar a{font:inherit;min-height:44px;border-radius:8px;padding:10px 15px;border:1px solid #c8cede;background:#fff;color:#343d65;text-decoration:none;cursor:pointer;font-size:12px;font-weight:600}button{background:#434d7d;color:#fff;border-color:#434d7d}.density-control{display:flex;align-items:center;gap:8px;font-size:12px;color:#4c5870;cursor:pointer}.density-control input{accent-color:#434d7d;width:18px;height:18px}
.preview-guidance{max-width:876px;margin:18px auto;color:#626e82;font-size:12px;padding:0 6px}.preview-guidance strong{color:#34405b}
.sheet{max-width:876px;margin:0 auto 36px;padding:40px 44px;background:#fff;border:1px solid #dce1eb;border-radius:6px;box-shadow:0 8px 35px #2631490b}
.document-header{display:flex;justify-content:space-between;align-items:flex-start;gap:22px;padding-bottom:24px;margin-bottom:25px;border-bottom:2px solid #434d7d}.brand{font-size:24px;font-weight:700;letter-spacing:-.6px;color:#283455;overflow-wrap:anywhere;min-width:0}.brand small{display:block;font-size:10px;letter-spacing:.2px;font-weight:400;color:#637086;margin-top:5px}.document-label{text-align:right;max-width:260px;min-width:0}.document-label strong{font-size:10px;letter-spacing:1.2px;color:#434d7d}.document-label small{display:block;font-size:10px;color:#657186;overflow-wrap:anywhere;margin-top:6px}
h1{font-size:27px;line-height:1.25;letter-spacing:-.8px;margin:0 0 9px;color:#1c2945;overflow-wrap:anywhere}.event-title{font-size:17px;font-weight:600;margin:0 0 13px;overflow-wrap:anywhere}.status{display:inline-block;font-size:11px;font-weight:600;padding:4px 10px;border-radius:5px;background:#edf7f1;border:1px solid #c4dfcf;color:#285b40}.status.pending{background:#fff7e7;border-color:#e9d8ad;color:#76571b}.status.cancelled{background:#fdf0ef;border-color:#eac7c2;color:#914c40}.version{font-size:11px;color:#667187;margin-left:9px}
h2{font-size:14px;letter-spacing:.2px;color:#273552;margin:26px 0 12px;padding-bottom:8px;border-bottom:1px solid #dce2ec}h3{font-size:12px;margin:0 0 6px;color:#384769}
.notice{padding:12px 14px;background:#f6f8fb;border:1px solid #e0e5ee;border-radius:7px;font-size:12px;color:#515f75;margin:16px 0;overflow-wrap:anywhere}.money-overview{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:23px 0;background:#f5f6fb;border:1px solid #dce1ef;border-radius:9px;padding:17px}.money-overview>div{min-width:0}.money-overview span{display:block;font-size:10px;color:#5b6880;margin-bottom:5px}.money-overview strong{font-size:19px;color:#2d3a5c;font-variant-numeric:tabular-nums;overflow-wrap:anywhere}.money-overview>div+div{border-left:1px solid #dce1ef;padding-left:15px}
.details{display:grid;grid-template-columns:1fr 1fr;gap:14px 28px;margin:22px 0}.detail{break-inside:avoid;min-width:0}dt{font-size:10px;color:#657187;margin-bottom:4px}dd{font-size:12px;font-weight:500;overflow-wrap:anywhere;margin:0;color:#1d2b43}
.menu-grid,.services{display:grid;grid-template-columns:1fr 1fr;gap:12px}.menu-section,.service-section{padding:14px 16px;border:1px solid #dce3ec;border-radius:7px;break-inside:avoid;min-width:0}.service-section>small{font-size:11px;color:#607087}ul{padding-left:16px;margin:5px 0 0;font-size:12px;color:#3f4d64}li{padding:2px 0;overflow-wrap:anywhere}
table{width:100%;border-collapse:collapse;font-size:12px;margin:12px 0;table-layout:fixed}th{font-size:10px;text-transform:uppercase;letter-spacing:.6px;background:#f3f5fa;color:#56647e;font-weight:600;text-align:left}th,td{padding:11px 10px;border-bottom:1px solid #e0e5ee;vertical-align:top;overflow-wrap:anywhere}.number{text-align:right;font-variant-numeric:tabular-nums;white-space:nowrap}.charges-table th:nth-child(1){width:45%}.charges-table th:nth-child(2){width:10%}.charges-table th:nth-child(3){width:21%}.charges-table th:nth-child(4){width:24%}.charges-table td:first-child{color:#253450;font-weight:500}.charges-table .number:last-child{font-weight:600}.totals{max-width:380px;margin:20px 0 0 auto;break-inside:avoid}.total-row{display:flex;justify-content:space-between;gap:18px;padding:9px 12px;font-size:12px;border-bottom:1px solid #e3e7ef}.total-row strong{white-space:nowrap;font-variant-numeric:tabular-nums}.total-row.major{font-size:18px;font-weight:600;border:1px solid #d9dfec;border-radius:7px;background:#f1f3fa;color:#2d3a5c}.total-row:last-child{font-weight:600;background:#f6f8fb;border-bottom:0;border-radius:0 0 7px 7px}
.financial-table{overflow-x:auto}.financial-table th:nth-child(1){width:24%}.financial-table th:nth-child(2){width:18%}.financial-table th:nth-child(3){width:32%}.financial-table th:nth-child(4){width:26%}.notes{padding:14px 16px;border-left:3px solid #b4bfd5;background:#f7f8fb;border-radius:0 6px 6px 0;font-size:12px;color:#3f4d65;white-space:pre-wrap;overflow-wrap:anywhere}.signatures{display:grid;grid-template-columns:1fr 1fr;gap:50px;margin-top:50px;break-inside:avoid}.signatures>div{border-top:1px solid #8995aa;padding-top:8px;color:#637087;font-size:10px}.footer{margin-top:27px;padding-top:14px;border-top:1px solid #dfe4ed;color:#657187;font-size:10px;line-height:1.8}.footer strong{color:#35415b}.no-margin{margin-top:0}tr{break-inside:avoid}thead{display:table-header-group}
.compact-print .sheet{padding:28px 36px}.compact-print .details{gap:8px 24px;margin:14px 0}.compact-print h2{margin-top:18px}.compact-print td,.compact-print th{padding-top:7px;padding-bottom:7px}.compact-print .menu-section,.compact-print .service-section{padding:9px 12px}.compact-print .menu-section ul,.compact-print .service-section ul{font-size:11px}.compact-print .document-header{margin-bottom:16px;padding-bottom:17px}
@media screen and (max-width:650px){body{font-size:14px}.print-toolbar{padding:12px 14px;gap:10px;flex-wrap:wrap}.print-toolbar>p{width:100%;font-size:11px}.toolbar-links{width:100%;gap:8px}.toolbar-links>a,.toolbar-links>button{flex:1;text-align:center;min-height:44px;padding:10px 8px}.density-control{width:100%;font-size:11px}.preview-guidance{margin:14px;padding:0;font-size:11px}.sheet,.compact-print .sheet{margin:0 8px 24px;padding:23px 17px;border-radius:9px}.document-header{flex-direction:column;gap:13px;padding-bottom:18px}.brand{font-size:23px}.document-label{text-align:left;max-width:none}.document-label small{font-size:10px}.document-label strong{font-size:10px}h1{font-size:23px}.event-title{font-size:16px}.money-overview{gap:10px;padding:14px;grid-template-columns:1fr}.money-overview>div{display:flex;align-items:center;justify-content:space-between;gap:12px}.money-overview>div+div{border-left:0;border-top:1px solid #dce1ef;padding:10px 0 0}.money-overview span{font-size:11px;margin:0}.money-overview strong{font-size:20px}.details{gap:14px;grid-template-columns:1fr 1fr}dd{font-size:12px}.menu-grid,.services{grid-template-columns:1fr}.version{display:block;margin:8px 0 0}.totals{max-width:none}.total-row{font-size:12px;padding:10px}.total-row.major{font-size:17px}.signatures{gap:24px;margin-top:45px}.charges-table thead{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}.charges-table tbody{display:block}.charges-table tr{display:grid;grid-template-columns:1fr 1fr 1.4fr;gap:8px;padding:13px 0;border-bottom:1px solid #dfe4ed}.charges-table td{padding:0;border:0;white-space:normal;font-size:12px}.charges-table td:first-child{grid-column:1/-1;font-size:13px}.charges-table td:before{content:attr(data-label);display:block;font-size:9px;color:#6b7586;font-weight:400;margin-bottom:3px}.charges-table td:first-child:before{display:none}.financial-table table{min-width:430px}.footer{font-size:10px}}
@page{size:A4;margin:13mm 14mm}@media print{body{background:white;font-size:9pt;color:#172133}.print-toolbar,.preview-guidance{display:none!important}.sheet,.compact-print .sheet{max-width:none;margin:0;padding:0;border:0;border-radius:0;box-shadow:none}.document-header{margin-bottom:18px;padding-bottom:17px}.brand{font-size:21pt}h1{font-size:20pt}h2{font-size:11pt;margin:19px 0 9px;break-after:avoid}h3{font-size:9pt;break-after:avoid}.event-title{font-size:12pt}.money-overview{margin:16px 0;padding:12px}.money-overview strong{font-size:15pt}.details{gap:10px 22px;margin:15px 0}dd{font-size:9pt}dt{font-size:8pt}table{font-size:9pt}th{font-size:8pt}td,th{padding:8px}.number{white-space:nowrap}.financial-table{overflow:visible}.menu-grid,.services{display:block;columns:2;column-gap:12px}.menu-section,.service-section{margin-bottom:10px;padding:10px 12px;break-inside:avoid;page-break-inside:avoid}ul,.notes{font-size:9pt}.total-row{font-size:9pt;padding:7px 10px}.total-row.major{font-size:13pt}.totals{margin-top:14px}.notice{font-size:9pt}.footer{font-size:8pt}.signatures{margin-top:35px}a{color:inherit;text-decoration:none}.compact-print .details{gap:7px 20px}.compact-print .menu-section ul,.compact-print .service-section ul{font-size:8pt}.compact-print h2{margin-top:15px}}

@media print{
 .separate-page{break-before:page}.agreement-details>h2:first-child{margin-top:0}.document-closing{break-inside:avoid}.document-closing .footer{margin-top:17px;padding-top:10px;font-size:7.5pt;line-height:1.6}.document-closing .signatures{margin-top:28px}
 .event-details{margin-bottom:18px}.service-details{margin-top:12px}.document-header{padding-bottom:13px;margin-bottom:15px}.notice{padding:9px 12px;margin:12px 0}.money-overview{margin:13px 0;padding:12px}.totals{max-width:350px}.menu-grid,.services{column-fill:balance}
 .compact-print .separate-page{break-before:page}.compact-print .document-closing .signatures{margin-top:22px}
}

.continuation-reference{display:none}@media print{.separate-page>.continuation-reference{display:block;font-size:8pt;color:#657187;border-bottom:1px solid #dfe4ed;padding-bottom:8px;margin-bottom:13px}.separate-page>h2{margin-top:12px}}

.empty-services{font-size:12px;color:#5d6a81;margin:16px 0;padding:7px 0;border-bottom:1px solid #e0e5ee}@media print{.empty-services{font-size:9pt;margin:9px 0;padding:5px 0}}
`;
