import { confirmationStyles } from './confirmation-styles.js';
import { durationDescription } from './booking-duration.js';
const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const amount = value => '₹'+(Number.isFinite(Number(value))?Number(value):0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
const date = value => {const d=new Date(value+'T00:00:00');return Number.isNaN(d.getTime())?String(value||'Not specified'):d.toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'});};
const featureList = values => values?.length ? `<ul>${values.map(value=>`<li>${escape(value)}</li>`).join('')}</ul>` : '';
export function renderConfirmation({booking:b,client={},payments=[],organization,format='full'}) {
 const financial=format==='full',q=b.quote,menu=q?.menu;
 const paid=payments.reduce((sum,p)=>sum+Number(p.amount||0),0);
 const title=b.status==='Confirmed'?'Booking confirmation':b.status==='Completed'?'Completed booking record':b.status==='Cancelled'?'Cancelled booking record':'Booking request — pending confirmation';
 const statusClass=['Confirmed','Completed'].includes(b.status)?'confirmed':b.status==='Cancelled'?'cancelled':'pending';
 const url='/api/bookings/'+encodeURIComponent(b.id)+'/confirmation';
 const detail=(label,value)=>`<div class="detail"><dt>${escape(label)}</dt><dd>${escape(value||'Not specified')}</dd></div>`;
 const charge=(label,value,quantity='',rate=null)=>`<tr><td>${escape(label)}</td><td class="number" data-label="Qty">${escape(quantity)}</td><td class="number" data-label="Rate">${rate===null?'':escape(amount(rate))}</td><td class="number" data-label="Amount">${escape(amount(value))}</td></tr>`;
 let charges='';
 if(financial){
  if(q){
   if(q.venueAmount)charges+=charge('Venue rental · '+(q.duration?.rateKey&&q.duration.rateKey!=='price'?'shift':'day'),q.venueAmount,q.duration?.rentalUnits||1,q.venueRate);
   if(q.cateringAmount)charges+=charge(`${q.plateType} catering · plates`,q.foodBase??q.cateringAmount,q.billedPlates,q.plateRate);
   if(q.minimumFoodTopUp)charges+=charge('Minimum food bill adjustment',q.minimumFoodTopUp);
   if(q.packageAmount)charges+=charge(q.plan.name+' · fixed package',q.packageAmount);
   for(const a of q.addonLines||[])charges+=charge(`${a.name} · ${a.unit}`,a.amount,a.quantity,a.rate);
   charges+=charge('Subtotal',q.subtotal);
   if(q.discount)charges+=charge('Discount',-q.discount);
   charges+=charge(`Tax / GST (${q.taxRate}%)`,q.taxAmount);
  }else charges=charge('Agreed booking amount',b.total);
 }
 const services=q?.addonLines||[];
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)} · ${escape(b.name)}</title><style>${confirmationStyles}
 </style><script src="/print-controls.js" defer></script></head><body>
 <nav class="print-toolbar" aria-label="Print options"><p>${financial?'Full copy includes prices and payments.':'Event-only copy excludes financial fields and payment terms.'}<br>Use “Save as PDF” in your browser’s print dialog.</p><div class="toolbar-links"><a href="${url}?format=${financial?'event':'full'}">${financial?'Event-only copy':'Full financial copy'}</a><button id="print-confirmation" type="button">Print / Save as PDF</button><label class="density-control"><input type="checkbox" id="compact-print">Compact layout · tighter spacing</label></div></nav><p class="preview-guidance"><strong>A4 print preview</strong> · Choose your printer or Save as PDF. Disable browser headers/footers for a cleaner document.</p>
 <main class="sheet"><header class="document-header"><div class="brand">${escape(organization)}<small>Celebration management · Gatherhall</small></div><div class="document-label"><strong>${financial?'BOOKING STATEMENT':'EVENT-ONLY COPY'}</strong><small>Booking reference: ${escape(b.id)}</small></div></header>
 <h1>${escape(title)}</h1><p class="event-title">${escape(b.name)}</p><span class="status ${statusClass}">${escape(b.status)}</span><span class="version">${financial?'Full financial details':'No financial details'}</span>
 ${b.status==='Pending'?'<div class="notice">This is a booking request, not a confirmed reservation. Please obtain confirmation from the venue.</div>':b.status==='Cancelled'?'<div class="notice">This booking is cancelled. This document does not confirm availability or reinstate the reservation.</div>':''}
 ${financial?`<section class="money-overview" aria-label="Financial summary"><div><span>Booking total</span><strong>${escape(amount(b.total))}</strong></div><div><span>Payments received</span><strong>${escape(amount(paid))}</strong></div><div><span>Balance remaining</span><strong>${escape(amount(Math.max(0,b.total-paid)))}</strong></div></section>`:''}
 <dl class="details event-details">${detail('Client',b.client+(financial?['',client.email,client.phone].filter(Boolean).map(v=>' · '+v).join(''):''))}${detail('Marriage hall',b.hall)}${detail('Event date',date(b.date))}${detail('Event / arrival time',b.time)}${detail('Reserved duration',durationDescription(b))}${detail('Event type',b.type)}${detail('Expected guests',b.guests)}${detail('Pricing model',q?.plan?.name||'Original manual booking')}</dl>
 ${financial?`<h2>Booking charges</h2><table class="charges-table"><thead><tr><th>Description</th><th class="number">Qty</th><th class="number">Rate (INR)</th><th class="number">Amount (INR)</th></tr></thead><tbody>${charges}</tbody></table><div class="totals"><div class="total-row major"><span>Booking total</span><strong>${escape(amount(b.total))}</strong></div>${q?`<div class="total-row"><span>Advance required (${escape(q.advancePercent)}%)</span><strong>${escape(amount(q.advanceAmount))}</strong></div>`:''}<div class="total-row"><span>Payments received</span><strong>${escape(amount(paid))}</strong></div>${q?`<div class="total-row"><span>Advance still due</span><strong>${escape(amount(Math.max(0,q.advanceAmount-paid)))}</strong></div>`:''}<div class="total-row"><span>Balance remaining</span><strong>${escape(amount(Math.max(0,b.total-paid)))}</strong></div></div>`:''}
 <section class="agreement-details ${financial&&(menu||services.length)?'separate-page':''}"><div class="continuation-reference">${escape(organization)} · ${escape(b.name)}<br>Booking reference: ${escape(b.id)}</div><h2>Event service details</h2><dl class="details service-details">${detail('Meal type',menu?.plateType||(q?.billedPlates?q.plateType:'Not recorded'))}${q?.version===2&&['plate','combined'].includes(q.plan.mode)?detail('Food billing basis',q.actualGuests===null?'Estimate from expected attendance':'Actual served recorded')+detail('Actual served guests',q.actualGuests===null?'Not recorded':String(q.actualGuests)):''}${q?.billedPlates?detail('Minimum / billable plates',`${q.guaranteedPlates} / ${q.billedPlates}`):''}${b.familyContact||b.familyPhone?detail('Family coordinator',[b.familyContact,b.familyPhone].filter(Boolean).join(' · ')):''}${b.baraatTime?detail('Baraat arrival',b.baraatTime):''}${b.muhuratTime?detail('Muhurat / ceremony',b.muhuratTime):''}${b.endTime?detail('Expected end time',b.endTime):''}</dl>

 <h2>Agreed food menu</h2>${menu?`<div class="menu-grid">${menu.sections.map(section=>`<section class="menu-section"><h3>${escape(section.name)}</h3>${featureList(section.items)}</section>`).join('')}</div>`:`<p class="notice">${q?.plan?.mode==='venue'?'Venue-only booking. No food menu is included.':'No itemized menu was recorded for this booking. Confirm the menu separately with the venue.'}</p>`}
 ${b.menuNotes?`<h2>Dietary / menu preferences</h2><div class="notes">${escape(b.menuNotes)}</div>`:''}
 ${services.length?`<h2>Selected extra services</h2><div class="services">${services.map(service=>`<section class="service-section"><h3>${escape(service.name)}</h3><small>Quantity: ${escape(service.quantity)} · ${escape(service.unit)}</small>${featureList(service.features)}</section>`).join('')}</div>`:'<p class="empty-services">No extra services were recorded.</p>'}

 ${financial?`<h2>Payment record</h2>${payments.length?`<div class="financial-table"><table><thead><tr><th>Date</th><th>Method</th><th>Reference</th><th class="number">Received</th></tr></thead><tbody>${[...payments].sort((a,b)=>a.date.localeCompare(b.date)).map(p=>`<tr><td>${escape(date(p.date))}</td><td>${escape(p.method)}</td><td>${escape(p.reference||'—')}</td><td class="number">${escape(amount(p.amount))}</td></tr>`).join('')}</tbody></table></div>`:'<p class="notice">No payments have been recorded.</p>'}<h2>Recorded booking terms</h2><div class="notes">${escape(q?.plan?.terms||'No model-specific terms were recorded. Refer to the separately agreed venue, payment and cancellation terms.')}</div>${b.notes?`<h2>Special requests</h2><div class="notes">${escape(b.notes)}</div>`:''}`:''}
 </section><div class="document-closing"><div class="signatures"><div>Venue representative · signature & date</div><div>Client / family representative · signature & date</div></div>
 <footer class="footer">${financial?'This is a booking record, not a statutory tax invoice. Payment amounts reflect entries recorded by the venue.':'This event copy intentionally excludes charges, payment records, general booking notes and financial terms.'}<br>Menu and service details are taken from this booking’s saved agreement, not today’s catalog. The reserved duration above controls venue availability. Ceremony/arrival times do not extend it. Food and fixed packages cover the agreed booking, not an automatic daily charge.</footer></div></main></body></html>`;
}
